"""Alumni registered through the Alumni Registration Form — generated, do not edit.

Written by tools/make-alumni-register.py from an export of the form's
responses, which is not in this repository. Each entry is the only thing the
school publishes from a registration:

    (institution key in alumni-destinations.json, name, years at CIRS, course)

196 entries from 224 responses. 13 responses named no institution that can be
placed and are left out.
"""

REGISTER = [
    ('alliance-university', 'K.P.Shrinidhi', '2014–2016', 'Bba'),
    ('alliance-university', 'Meghna Rajendran Nambiar', '2007–2012', 'BBM'),
    ('american-graduate-school-in-paris', 'Prarthana Lohia', '2008–2010', 'BBA Hons/ Certificate in NGO Management'),
    ('amity-university', 'Shreeyal Khandelwal', '2008–2014', 'Psychology'),
    ('amity-university', 'Veenaa Annamalai', '2013–2015', 'Anthropology'),
    ('amity-university-noida', 'Ketan Manepalli', '2013–2015', 'Integrated MBA'),
    ('amrita-school-of-engineering', 'Prasita', '2006–2008', 'B.Tech'),
    ('amrita-vishwa-vidyapeetham', 'Ariharan.N', '2013–2015', 'B-tech Aerospace'),
    ('amrita-vishwa-vidyapeetham', 'Athira Sreekumar Nair', '2011–2013', 'B.tech'),
    ('amrita-vishwa-vidyapeetham', 'Pasunuri Sathyapriya', '2006–2009', 'B-tech'),
    ('anna-university', 'Nanthithashanmuhasundaram', '2002–2010', 'Bsc AFT'),
    ('anna-university', 'Shruti Jayaraman', '2010–2012', 'Instrumentation and Control'),
    ('bangalore-university', 'Sharnya Raajeev', '1996–1998', 'BCA'),
    ('bits-pilani-dubai-campus', 'Aadit Tibrewal', '2010–2014', 'Engineering'),
    ('bits-pilani-dubai-campus', 'Krishna Rajesh Nair', '2013–2015', 'Chemical Engineering'),
    ('bukovinian-state-medical-university', 'Krishna Taneja', '2006–2011', 'Doctor of Medicine'),
    ('cardiff-university', 'Shruti Kedia', '2007–2009', 'MA International Journalism'),
    ('carnegie-mellon-university', 'Arun Sriram Chockalingam', '2011–2015', 'Materials Science and Engineering/Biomedical Engineering - Double Major'),
    ('christ-university', 'Chirantan Saha', '2008–2014', 'BBA'),
    ('christ-university', 'Gopal Jindal', '2012–2014', 'BBA'),
    ('christ-university', 'Kalansh Gla', '2007–2011', 'Theatre Studies'),
    ('christ-university', 'Maahi Agarwal', '2017–2018', 'BBA IN FINANCE AND ACCOUNTS'),
    ('christ-university', 'Mitun Gunasekar', '2006–2014', 'BBA(Hons)'),
    ('christ-university', 'Mukund Sarda', '2008–2012', 'BBA'),
    ('christ-university', 'Naman Agarwal', '2011', 'BBA'),
    ('christ-university', 'Shivaa B', '2012–2014', 'B.Com'),
    ('christ-university', 'Srijan Seth', '2012–2014', 'Bcom Professional'),
    ('college-of-architecture-trivandrum', 'Bharat Mitra Nanda', '2011–2013', 'Architecture'),
    ('college-of-engineering-guindy-anna-university', 'Ramakrishnan Nagarajan', 'until 2008', 'BE'),
    ('cornell-university', 'Amrutha Anandaraman', '2008–2010', 'M.S Food Science'),
    ('curtin-university', 'S Prashaanthi', '1998–2004', 'Bachelor of Commerce - Accounting & Information Systems'),
    ('dayanand-sagar-university', 'Sakshi Shetty', '2010–2015', 'BA Journalism'),
    ('delhi-university', 'Sahjeet Menon', '2007–2012', 'BMS'),
    ('doon-business-school-and-allied-sciences', 'Rahul Tharun. A', '2018–2020', 'Bsc forestry'),
    ('dy-patil-school-of-medicine', 'Ashna Jagtiani', '2007–2013', 'MBBS'),
    ('emory-university', 'Hiren Suraiya', '2011–3013', 'Liberal Arts (Economics and Computer Science)'),
    ('faculty-of-management-studies', 'Vidisha Sarawagi', '2007–2011', 'MBA'),
    ('fairleigh-dickinson-university', 'Kushal Vaswani', '2000–2004', 'MBA (Finance)'),
    ('fergusson-college', 'Pooja Lakshmaan', '2009–2011', 'BA English'),
    ('flame-university', 'Pranav Goenka', '2009–2014', 'BBA'),
    ('florida-institute-of-technology', 'Niket Ghelani', '2003–2008', 'BS Mechanical Engineering'),
    ('george-brown-college', 'Meghna Nambiar', '2007–2012', 'Sport and Event Marketing'),
    ('georgia-institute-of-technology', 'Ankit Tibrewal', '2002–2009', 'Industrial & Systems Engineering'),
    ('georgia-institute-of-technology', 'Rachit Kejariwal', '2005–2010', 'Mechanical Engineering'),
    ('glasgow-caledonian-university', 'Yash Gogri', '2002–2004', 'MSc Finance'),
    ('gujarat-university', 'Aditya', '2002–2007', 'Commerce'),
    ('hkust', 'Pranesh Balekai', '2011–2013', 'Electronics and computer engineering'),
    ('hkust', 'Varun Fatehpuria', '2008–2013', 'BBA(IS&Finance)'),
    ('hofstra-university', 'Yash Udaybhai Tilva', '2009–2011', 'Supply Chain Management'),
    ('hr-college', 'V Susheeth Kumar', '2006–2014', 'Bcom'),
    ('htmi-switzerland', 'Sibhi Manoharan', '2001–2006', 'PGD in international hotel and tourism management'),
    ('ibs', 'Sumit Kumar Drolia', 'from 1998', 'Mba'),
    ('icfai', 'Prasanth Kumar', '2002–2006', 'MBA'),
    ('iitm', 'Rani Unnamalai K', '2008–2015', 'Integrated M.A'),
    ('indian-school-of-design-and-innovation-parsons-mumbai', 'Janamejay', '2005–2012', 'Communication Design'),
    ('inifd', 'Vedika Sharma', '2005–2009', 'INTERIOR DESIGN'),
    ('institute-of-chartered-accountants-of-india', 'Adithya Ravesanker', '2009–2011', 'Chartered Accountancy'),
    ('institute-of-chartered-accountants-of-india', 'Ankit G Kataria', '1996–2002', 'CHARTERED ACCOUNTANT'),
    ('institute-of-chartered-accountants-of-india', 'Chodavarpu Raviteja', '2009–2011', 'CA'),
    ('institute-of-chartered-accountants-of-india', 'Prannay Jain', '2006–2010', 'Chartered Accountant'),
    ('institute-of-chartered-accountants-of-india', 'Sarthak Ranasaria', '2011–2013', 'Chartered Accountancy'),
    ('institute-of-chartered-accountants-of-india', 'Thanmayi AG', '2006–2008', 'Chartered Accountancy'),
    ('institute-of-law-nirma-university-ahmedabad', 'Meetali Agarwal', '2008–2010', 'B. Com LLB (Hons.)'),
    ('institute-of-management-technology', 'Shubha Goyal', '1996–2001', 'MBA'),
    ('j-d-birla-institute', 'Prarthana Lohia', '2008–2010', 'BBA Hons/ Certificate in NGO Management'),
    ('jadavpur-university', 'Achyut Todi', '2005–2013', 'Bachelor of Business Administration'),
    ('jai-hind-college', 'Pavan Shah', '2008–2013', 'BAF (or) Bachelors of Commerce in Accounting & Finance'),
    ('jain-university', 'Arjun Mundra', '2008–2011', 'BBA'),
    ('james-cook-university-singapore', 'Paul George', '1999–2004', 'MBA'),
    ('james-cook-university-singapore', 'Shreya Karthikeyan', '2012–2014', 'Bachelor of Business'),
    ('kaplan-higher-education-academy', 'Archana Pradeep Kumar', '2013–2015', 'Diploma in Cyber forensics'),
    ('karunya-university', 'Siddharth Roy', '2006–2010', 'M.Tech'),
    ('kiit-university', 'Adarsh Agrawal', '2004–2009', 'B.Tech ( Civil Engineering )'),
    ('kirori-mal-college', 'Devanshu Agarwal', '2013–2015', 'Bcom honors'),
    ('kumaraguru-college-of-technology', 'Aswni Sundara Rajan', '2013–2015', 'Biotechnology'),
    ('kumaraguru-college-of-technology', 'Raveena Retnakumar', '2012–2014', 'Engineering'),
    ('loyola-college', 'Shree Ram Kumar', '2008–2012', 'BBA'),
    ('m-o-p-vaishnav-college-for-women', 'Diksha Tandon', '2011–2013', 'B.Sc Visual Communication'),
    ('m-o-p-vaishnav-college-for-women', 'Madhu Vandhani', '2007–2009', 'MBA'),
    ('m-o-p-vaishnav-college-for-women', 'Vaishnavi Srinath', '2009–2011', 'BBA'),
    ('m-s-ramaiah-institute-of-technology', 'Varun Agarwal', '2006–2010', 'B.E'),
    ('maharashtra-institute-of-technology-school-of-management', 'Abhiishek Krishnan', '2011–2013', 'Bachelors in Business Management (International Business)'),
    ('manipal-institute-of-technology', 'Haswanth', '2011–2016', 'Computer and communication engineering'),
    ('manipal-institute-of-technology', 'Varun Harnathka', '2008–2011', 'Chemical Engineering'),
    ('manipal-university', 'Bharath Krishna', '2006–2013', 'Chemical engineering'),
    ('manipal-university', 'Praachi Singh', '2006–2008', 'MBBS'),
    ('manipal-university', 'Priya Singh', '2007–2008', 'MBBS'),
    ('manipal-university', 'Shriya Atmakuri', '2012–2014', 'B.Tech Computer Science'),
    ('manipal-university', 'Vedang Gutgutia', '2011–2013', 'BTech Computer Science Engineering'),
    ('mc-gans-ooty-school-of-architecture', 'Sarath Chandran', '2010–2012', 'B.Arch'),
    ('mdis', 'Minati Hingorani', '2011–2013', 'Bsc (hons) business and management studies'),
    ('mithibai-college', 'Shrishti Gadodia', '2007–2015', 'Bachelor of Management Studies'),
    ('mount-carmel-college', 'Sonal Agrawal', '2008–2013', 'Bba'),
    ('national-institute-of-bank-management', 'Lakkaraju Sai Anurag', '2008–2010', 'Post Graduate Diploma in Management (Banking and Financial Services)'),
    ('national-institute-of-technology-tiruchirappalli', 'Aashish Bohra', '2009–2011', 'Bachelor of technology in Production Engineering'),
    ('national-institute-of-technology-tiruchirappalli', 'Mukesh Raj', '2013–2015', 'MECHANICAL ENGINEERING'),
    ('national-institute-of-technology-tiruchirappalli', 'Shashank Sreekar B', '2011–2013', 'B.Tech Civil Engineering'),
    ('nlu-delhi', 'Arpit Agrawal', '2008–2012', 'BALLB'),
    ('nmims', 'Anuj Agrwal', '2013–2015', 'BBA'),
    ('nmims', 'Ashutosh Bohra', '2008–2015', 'B. Sc Economics'),
    ('nmims', 'Deva Narayan', '2005–2010', 'MBA'),
    ('nmims', 'Nidhi Agarwal', '2012–2014', 'Btech extc'),
    ('nmims', 'Radhika Rawat', '2013–2015', 'B. Sc. Applied Statistics and Analytics'),
    ('nmims', 'Varun Chitalia', '2005–2007', 'MBA'),
    ('nmims', 'Yukti Sarawgi', '2013–2015', 'BBA'),
    ('nmims-balwant-seth-school-of-architecture', 'Shikha Patel', '2012–2014', 'Bachelor of Architecture'),
    ('nyu', 'Sarvesh Mathiyazhagan', '2010–2015', 'BA. Economics and CS'),
    ('o-p-jindal-global-university', 'Krittika Bhawsar', '2011–2013', 'B.A, LL.B (Hons.)'),
    ('oxford-brookes-university', 'Niketa Ranjan', '2008–2014', 'Architecture'),
    ('pearl-academy', 'Tulsi Jayesh Thakkar', '2008–2015', 'Luxury brand management'),
    ('ppg-institute-of-technology', 'Saroj Saran', '2009–2014', 'Engineering'),
    ('prin-l-n-welingkar-institute-of-management-development-research', 'Neeraj Parmanandka', '1996–2002', 'PGDBM'),
    ('psg-college-of-technology', 'K. Sanjith Gurubaran', '2007–2015', 'B. Tech textile technology'),
    ('psg-college-of-technology', 'Kiran Yashwanth', '2010–2015', 'BE automobile'),
    ('psg-institute-of-technology', 'S Sithsabesan', '2008–2015', 'B.Tech IT'),
    ('purdue', 'Prit Chovatiya', '2010–2015', 'Aeronautical and Aerospace Engineering'),
    ('purdue', 'Taruna Jagtiani', '2008–2015', 'Medical laboratory science'),
    ('rochester-institute-of-technology', 'Raj Bhalala', '2004–2006', 'BS Mechanical Engineering Technology'),
    ('royal-holloway-university-of-london', 'Bhargav Nagesh Nannapaneni', '2009–2013', 'MSc International Management (Marketing)/ MBA'),
    ('sardar-patel-university', 'Athul Binesh', '2013–2015', 'B.arch'),
    ('savitribai-phule-pune-university', 'Taruun Vaiddya', '2006–2008', 'BE Mechanical'),
    ('school-of-allied-health-sciences-manipal-university', 'Vijayapriya CV', '2004–2010', 'M.Phil. Clinical Psychology'),
    ('school-of-inspired-leadership', 'Chandan Sangal', '2001–2003', 'MBA - HR'),
    ('school-of-planning-and-architecture', 'Gayathri Venkatraman', '2008–2015', 'B.Arch'),
    ('shiv-nadar-university', 'Kashyap Jothish', '2009–2014', 'B.Tech Mechanical Engg.'),
    ('shri-devraj-urs-medical-university', 'Mowthi Karuna', '2005–2011', 'MBBS'),
    ('sp-jain-school-of-global-management', 'Sai Bharat', '2011–2013', 'BBA'),
    ('srcc', 'Vineet Lohariwal', '2010–2012', 'B.com honours'),
    ('sri-sri-university', 'Aravind Sreekumar Menon', '2014–2015', 'B.Com'),
    ('sri-venkateswara-college', 'Nishant Agarwal', '2009–2015', 'B.com(P)'),
    ('srishti-university-of-art-design-technology', 'Amantrika Saraogi', '2010', 'Visual communication and strategic branding'),
    ('srm-institute-of-science-and-technology', 'S.S.Arunadithys', '2007–2012', 'MECHANICAL ENGINEERING'),
    ('st-joseph-s-college-of-arts-and-science', 'Niyati Harnathka', '2007–2011', 'M.A. English Literature'),
    ('st-joseph-s-college-of-arts-and-science', 'Tanya Kini', '2009–2011', 'B.A. History, Economics, Political Science'),
    ('st-joseph-s-college-of-commerce-bengaluru', 'Adarsh Bhaskar Kulkarni', '2013–2015', 'B.com + ACCA'),
    ('st-joseph-s-college-of-law', 'Tanmayee Naidu', '2011', 'BBA LLB'),
    ('st-xavier-s-college-kolkata', 'Akash Kedia', '2012–2014', 'B.Com(Honors)'),
    ('st-xavier-s-college-kolkata', 'Anish Sardana', '2012–2014', 'B.COM(Honors)'),
    ('st-xavier-s-college-kolkata', 'Ayush Mittal', '2010–2015', 'B.COM (H)'),
    ('st-xavier-s-college-kolkata', 'Urvi Gupta', '2013–2015', 'B.com. hons.'),
    ('st-xavier-s-college-mumbai', 'Shubhankar Sarda', '2010–2012', 'B.Sc. Physics'),
    ('st-xavier-s-college-ranchi', 'Devesh Jain', '2004–2009', 'B.Com Accounts Honors'),
    ('symbiosis-centre-for-management-studies', 'Mannava Sarath Chandra', '2012–2014', 'BBA'),
    ('symbiosis-centre-for-media-and-communication', 'Devika Menon', '2013–2015', 'Mass Communication'),
    ('symbiosis-centre-for-media-and-communication', 'Shyam Mohan', '2013–2015', 'BA Mass Communication'),
    ('symbiosis-college-of-arts-and-commerce', 'Shrutika Rastogi', '2012–2014', 'Bcom+CA'),
    ('symbiosis-institute-of-media-and-communication', 'Lakshmi Menon', '2010–2012', 'MBA in communication management'),
    ('symbiosis-international-university', 'Govindshankar Krishnan', '2008–2010', 'BBA Llb'),
    ('symbiosis-international-university', 'Saurabh Bhandari', '2007–2009', 'Masters in Audio Visual Production'),
    ('symbiosis-school-of-economics', 'Paul Arun Kunnil', '2013–2015', 'Bsc. Economics'),
    ('t-a-pai-management-institute', 'Anup Kataria', '1996–2002', 'MBA'),
    ('the-university-of-hong-kong', 'Kushal Aggarwal', '2008–2012', 'Bachelors of economic and finance'),
    ('university-college-london', 'Shreyans Bafna', '2009–2011', 'Construction Economics and Management'),
    ('university-of-bradford-singapore', 'Vandana Vaswani', '2009–2013', 'Accounting and Finance'),
    ('university-of-bristol', 'Lakshan Ram Madhan Mohan', '2012–2014', 'Msci Physics'),
    ('university-of-british-columbia', 'Akshay Krishna S', '2009–2015', 'Biological Sciences'),
    ('university-of-british-columbia', 'Pranav Menon', '2012–2014', 'Engineering'),
    ('university-of-california-irvine', 'Suryanshi Rakesh Pandya', '2007–2013', 'Education Sciences'),
    ('university-of-canterbury', 'Vivek Thirani', '2006–2009', 'Master in Engineering Studies (Construction Management)'),
    ('university-of-illinois-urbana-champaign', 'Bharat Poddar', '2000–2004', 'Bachelor of Science - Electrical Engineering'),
    ('university-of-liverpool', 'Arun Anantha Narayanan', '2011–2015', 'BA Accounting and Finance with a Year in Industry'),
    ('university-of-london-singapore', 'Harnita Ramamurthy', '2004–2005', 'B.Sc Economics and Management'),
    ('university-of-madras', 'Abhishek Prahalad Prakash', '2010–2012', 'Bcomm (G)'),
    ('university-of-mumbai', 'Anirudh Modi', '2009–2012', 'Bachelor in Accounting and Finance'),
    ('university-of-mumbai', 'Dhruvi Dwivedi', '2009–2011', 'Bachelor of architecture'),
    ('university-of-mumbai', 'Nishit Ghelani', '2003–2010', "Bachelor's Of Management Studies"),
    ('university-of-mumbai', 'Parth Sarda', '1996–2001', 'BCom'),
    ('university-of-mumbai', 'Vedanti Rajendra Shinde', '2012–2014', 'Bachelor of Arts'),
    ('university-of-new-south-wales', 'Harini Jaiswathi', '2007–2015', 'Bachelor of commerce'),
    ('university-of-nottingham', 'Adithya Anandaraman', '2006–2008', 'Finance'),
    ('university-of-nottingham', 'Ankit Mohata', '2007–2009', 'BA (hons) Finance, Accounting & Management'),
    ('university-of-petroleum-and-energy-studies', 'Manish Chinmay', '2013–2015', 'B.Tech in Mechatronics'),
    ('university-of-scranton', 'Bharath Ram Madhan Mohan', '2010–2013', 'Entrepreneurship/Marketing'),
    ('university-of-sheffield', 'Harleen Gokaldas', '2012–2014', 'Genetics'),
    ('university-of-southern-california', 'Vidhi Todi', '2011–2013', 'Communication + Fine Arts'),
    ('university-of-sydney', 'Bharath Santhosh', '2012–2018', 'Bachelor in Engineering Honours (Mechatronics)'),
    ('university-of-the-arts-london', 'Nibedita Satpathy', '2006–2008', 'BA (Hons) Fashion Management'),
    ('university-of-toledo', 'Gayatri Subramanian', '2006–2007', 'PhD Biomedical Sciences'),
    ('university-of-victoria', 'Aakash Rao', '2003–2010', 'Mechanical Engineering'),
    ('university-of-waterloo', 'Adarsh Hinduja', '2012–2014', 'Computer Science'),
    ('university-of-waterloo', 'Pranav Shankar Subramani', '2012–2014', 'Bmath Combinatorial Optimization and Bachelors in Computer Science.'),
    ('university-of-waterloo', 'Sanjay Krishna', '2012–2014', 'B.Math Mathematical Physics'),
    ('university-of-westminster', 'Bhargav Nagesh Nannapaneni', '2009–2013', 'MSc International Management (Marketing)/ MBA'),
    ('university-of-wisconsin-madison', 'Ritvind Suketana', '2012–2014', 'Chemical Engineering'),
    ('university-of-wollongong', 'Nikita Shan Kumar', '2008–2010', 'Bcom HR'),
    ('university-of-wollongong-in-dubai', 'Honey Tolani', '2012–2014', 'BBA'),
    ('utkal-university', 'Vishakha Patnaik', '2001–2004', 'Bba'),
    ('vellore-institute-of-technology', 'Jishnu Sudhir Nair', '2009–2011', 'Mechancial Engineering'),
    ('vellore-institute-of-technology', 'Mudit Bhartia', '2011–2016', 'Computer Science Engineering'),
    ('vellore-institute-of-technology', 'Parimala.M.Nair', '2009–2015', 'Btech biotechnology'),
    ('visvesvaraya-technological-university', 'Arpit Agarwal', '2008–2011', 'BE - Mechnical'),
    ('visvesvaraya-technological-university', 'Harshkunj Prashant Chokhawala', '2007–2009', 'BE'),
    ('visvesvaraya-technological-university', 'Vaibhav Purohit', '2010–2010', 'BE in Information Science'),
    ('warwick', 'Lakshmi Ajay', '2013–2015', 'Film and Literature'),
    ('warwick', 'Shreya Gupta', '2005–2011', 'Economics'),
    ('york-university', 'Shubha Kumar Kaushik', '2010–2015', 'Communication Studies'),
]
