#!/usr/bin/env python3
"""The articles the CIRS Blog publishes, taken from The Crossroads.

Every word below is the magazine's. Each article was lifted from the issue
PDF in assets/source/crossroads-pdf/ and is reproduced whole — no summaries,
no rewriting, and nothing added. Issues 2, 4, 17, 30, 31 and 32 carry a text
layer and were extracted from it; issue 29 was exported as flat images and
had to be transcribed by hand from the page.

The only changes made to any of it are plain corrections of spelling,
punctuation and grammar, at the school's request — a misspelt name, a comma
that should have been a full stop, a duplicated word. Two factual slips in
"Trust or Bust" were deliberately left alone, because correcting them means
deciding what the author meant: it announces four outcomes and lists three,
and the sentence that mutual defection earns is five years in one paragraph
and three in another. Its byline is not printed anywhere in the issue and
was supplied by the school.

To publish another article: add its entry here with its paragraphs, and
build-site.py gives it a page and the feed gives it a card. Nothing else has
to change.
"""

POSTS = [
    {
        "slug": "death-of-rationalism",
        "title": "The Death of Rationalism",
        "issue": 32,
        "date": "August 2026",
        "author": None,
        "section": "Opinion",
        "image": "death-of-rationalism.webp",
        "image_alt": "Illustrated stone hall breaking apart between geometric lines and dark smoke",
        "image_width": 941,
        "image_height": 1672,
        "image_caption": "Illustration supplied for the web edition.",
        "excerpt": "Rationalism was meant to be a method, not an identity. It was to be the discipline of honest seeing, not another tribe of the like-minded. You question, you examine, you see clearly.",
        "paragraphs": [
            "Rationalism was meant to be a method, not an identity. It was to be the discipline of honest seeing, not another tribe of the like-minded. You question, you examine, you see clearly. You hold no belief sacred, no authority exempt — including your own. Every conclusion must justify itself and if it cannot, you let it go. That is the original promise. From the Greek sceptics to the Enlightenment philosophers to the modern scientific temper, this is what rationalism has always claimed as its essence: the courage to ask, the willingness to discard, the refusal to bow before any idea simply because it is old or revered or comfortable.",
            "The courage to question rather than blindly obey, to examine rather than merely accept: this is what allows the mind to mature and society to remain free.",
            "None of this is an argument against rationalism as a method. The method works. Peer review catches errors, replication weeds out fraud, falsification disciplines speculation. The institution of science corrects what the individual scientist cannot. But the method’s virtue does not automatically transfer to the practitioner. A system can be self-correcting while the people within it remain thoroughly self-deceived. It is this gap, between what rationalism promises and what the rationalist practices, that concerns us here.",
            "The Outward Gaze Watch the rationalist in action. He will tell you precisely why the pilgrim is wasting his time at the temple, but he cannot tell you why he himself spent three hours last night arguing with strangers on the internet. He will explain the cognitive biases that make people believe in astrology, yet he has never once examined the compulsion that makes him need to correct them. He writes essays on why people cling to tradition.",
            "Still, he cannot see that his own identity as “the one who sees through tradition” is just as clung to, just as defended, just as psychologically necessary to him as any ritual is to a devotee.",
            "This is the fatal flaw. Reason directed only outward is not complete reason; it is half-reason, and half-reason is often more dangerous than no reason at all because it comes with the illusion of completeness.",
            "The religious believer at least knows he believes. The rationalist who has made reason into identity does not know he believes; he thinks he merely sees. And so his beliefs operate unchecked, unexamined, all the more powerful for being invisible. Belief in reason is something else entirely. It is reason frozen into dogma, producing certainty rather than clarity, positions rather than understanding, debates rather than insight. The believer in reason has made rationality into a flag, and he will defend that flag as fiercely as any religious zealot defends his scripture.",
            "His positions are not held because they are true but because they are his; his arguments are not aimed at understanding but at victory. His rationalism has become, in everything but name, a faith.",
            "The Of Death Rationalism Rationalism Rationalism Rationalism This is the questioning the ego cannot survive. It can survive any external argument; it can change positions, update beliefs, switch tribes, and remain fundamentally intact. What it cannot survive is being seen.",
            "This is why self-enquiry is so rare, and why it is so essential. The rationalist who has never asked, “What am I really doing when I argue?”, who has never noticed the pleasure in being right, the fear of being wrong, the satisfaction of superiority, has never used reason fully. He has used reason the way a child uses a stick: to hit things, defend territory, feel powerful. He has not yet used reason the way a surgeon uses a scalpel: to cut through illusion, beginning with his own.",
            "The bars are elegant, the locks are logical, and the prisoner is convinced he is free because he can critique the cages of others. But he remains inside, for he has never questioned the one who built the cage, who maintains the cage, who is terrified of life outside the cage. His cage has a sign on it that says “No Cage,” and he believes the sign.",
            "Liberation is not a change of content; it is freedom from the need to cling to any content. The liberated mind can hold positions without being held by them, can use reason without being used by the ego’s need for reason, can think without needing thought to tell it who it is.",
            "This liberation is not achieved by abandoning rationalism; it is achieved by completing it, by turning the light that has illuminated so much of the external world, finally, uncompromisingly, on the one who holds the light.",
            "Rationalism without self-enquiry cannot see its own motivations. Fear, insecurity, superiority, the need to be right — these operate freely beneath the language of logic. The rationalist believes he is defending truth, but he does not see that he is defending himself. He believes he is exposing others’ irrationality, but he does not see the irrationality of his own emotional investment in being the one who exposes.",
            "Reason is then used to justify psychological compulsions rather than dissolve them. The ego learns to speak in syllogisms; it marshals data the way a lawyer marshals precedents, not to find truth but to win the case. And the case is always the same: I am right, I am rational, I am superior to those who are not.",
            "In certain Western rationalist circles, approved conclusions function as membership tests. Deviate, even carefully and with evidence, and you are not refuted but reclassified: you become a denialist, a bigot, someone who has “revealed their true colors.” The argument is not answered; the arguer is diagnosed. Among several Indian rationalists, the pattern mirrors. One must hold the correct contempt for all religion and the “correct” suspicion of all tradition. Suggest that an ancient text contains genuine philosophical insight, and you risk being treated as a communal apologist; question whether one particular civilizational model is the only path to human flourishing, and you become intellectually untouchable.In both cases, the permitted conclusions are known in advance, and argument no longer exists to discover truth but to police boundaries. This is not reason at work; it is the ego defending its shelter, now speaking the language of rationality.",
            "Try it now. Pick a position you hold dear, one you have defended publicly, one that feels obviously correct. Ask: what do I get from holding this? Not what is true about it, but what does it give me? Watch what arises. If the mind rushes to justify the position, that rush is the answer. If irritation arises at the question itself, that irritation is the answer. Self-enquiry does not require you to abandon your conclusions; it only asks you to see who is clinging to them, and why.",
            "This liberation is not achieved by abandoning rationalism; it is achieved by completing it, by turning the light that has illuminated so much of the external world, finally, uncompromisingly, on the one who holds the light.",
            "The question is not whether you can question religion, tradition, politics, or superstition; you have already demonstrated that capacity. The question is whether you can question the questioner. Can you ask, with genuine notknowing: What am I defending? What am I afraid of? Who would I be if I could no longer call myself rational?",
            "Begin there. That is the only beginning worth the name. Refuse, and you remain what you have always been: an ego armed with arguments, a prisoner who has memorised every book on liberation but never bothered to look at his own chains.",
        ],
    },
    {
        "slug": "beyond-the-lobby",
        "title": "Beyond the Lobby",
        "issue": 32,
        "date": "August 2026",
        "author": "Muhil T. | IB I Yr",
        "section": "Culture",
        "image": "beyond-the-lobby.webp",
        "image_alt": "Armoured video game soldier holding a rifle",
        "image_width": 1920,
        "image_height": 1080,
        "image_caption": "Illustration supplied for the web edition.",
        "excerpt": "A digital world where millions come togethersome for a living, some for leisure, some for addiction, and some for peace.",
        "paragraphs": [
            "A digital world where millions come togethersome for a living, some for leisure, some for addiction, and some for peace. Deafening gunshots and unpredictable maps: the battleground isn't only found in massive PlayStation consoles or an expensive PC rig—it’s compressed into the palm of your hand, radiating heat, chaos, and adrenaline. Welcome to Call of Duty: Mobile. In a game where victory is decided in milliseconds, strategy isn't the only thing that backs you: it's the agile human reflexes that do their magic.",
            "Every player has his own custom layout and style of gameplay, be it rushing to the enemy’s base in multiplayer, camping with a sniper in a hidden spot, or splitting within the squad in Battle Royale to avoid team wipeouts. A professional gamer spends at least 6-10 hours a day pushing his rank and stacking victories. Older generations love to warn us that gaming is just a mindless, addictive distraction, but fast-paced games like Call of Duty: Mobile actually give your brain a serious workout.",
            "Constantly scanning small screens for tiny movements sharpens your spatial awareness and forces your mind to process information much faster than it normally would. A missed glare from a sniper’s scope can cost a match. Overlooking a fighter jet nearby can kill the entire squad. Neuroscience proves this isn’t just theory: In a landmark tracking test, action gamers completely outperformed non-gamers in hand-eye coordination, scoring an average of 293 compared to just 162 —marking a near 55% reduction in precision errors.",
            "Adding to this, a University of Toronto study confirmed that playing fast-paced shooters like Call of Duty explicitly rewires the brain to absorb and master new real-world sensorimotor tasks drastically faster than the general population. Every tap of the finger is coordinated, and even the shadows are not left unseen. Gamers are known for their superhuman reflexes. But these sharp reflexes and rewired neural pathways are just the basic physical entry requirements.",
            "The true value of this modern playground isn't measured in milliseconds or high scores; rather, it's about how it helps us grow, connect, and bounce back. When a player logs in, they aren't just escaping reality; they are entering an arena that demands immediate collaboration, emotional regulation under constant pressure, and a culture of constancy where failure is never a final defeat but a lesson. In a world that often isolates us, gaming has quietly become a shared community where global friendships are built.",
        ],
    },
    {
        "slug": "anakin-skywalker",
        "title": "Anakin Skywalker and the Poetics of Tragedy",
        "issue": 32,
        "date": "August 2026",
        "author": "Aayush S. B. | IB II Yr",
        "section": "Culture",
        "image": "anakin-skywalker.webp",
        "image_alt": "William Shakespeare holding a blue lightsaber and a copy of Hamlet against a galactic backdrop",
        "image_width": 1024,
        "image_height": 559,
        "excerpt": "The Star Wars prequel is, at its core, a tragedy. Yet within popular discourse it has long been dismissed as pulp science fiction; a spectacle over substance sort of material.",
        "paragraphs": [
            "The Star Wars prequel is, at its core, a tragedy. Yet within popular discourse it has long been dismissed as pulp science fiction; a spectacle over substance sort of material. This article resists that dismissal. It reads Star Wars Episode III: Revenge of the Sith (2005), contrary to popular claim, not as blockbuster cinema, but as a literary text, and subjects its dialogue to the same scrutiny one might apply to Sophocles or Shakespeare.",
            "The central claim lies in this: The dialogue in Revenge of the Sith (both Anakin's own speech and the exchanges constructed around him) functions as a deliberate literary mechanism that builds him into a recognizable tragic hero, one whose contours are shaped by the conventions Aristotle delineated in the Poetics and which recur across the tragic canon from Oedipus to Macbeth. The analysis is mainly modelled around four Aristotelian categories: Hamartia (The fatal flaw that initiates the flaw), Peripeteia (the reversal of fortune), Anagnorisis (the moment of recognition), and the cathartic effect produced in the audience through Eleos and Phobos (pity and fear).",
            "Aristotle’s Hamartia works not as vice but as frailty, an imperfection indigenous to the hero’s own nature, not imposed on him from without. In Anakin, this frailty takes the shape of a love so absolute it cannot tolerate the ordinary erosions of mortality, wedded to a conviction that sufficient will can bend even fate to heel. The seed of this flaw is sown in Episode II: Attack of the Clones, in the aftermath of his mother’s death, when he confesses the massacre of the Tusken Raiders to Padmé, with fury, rather than grief or regret.",
            "This fury resolves into 3 words that indict the greater picture rather than himself, or the cosmos, if I may: “it’s not fair.” Here, in embryonic form is the tragedy entirely: a boy who cannot reconcile himself to a universe indifferent to his longing.",
            "By Revenge of The Sith, this same inability of reconciliation has fastened itself to Padmé. When Anakin confesses that he has seen her death, “As clearly as I see you now”, the line performs a double labor, it renders his devotion total, and it exposes his relationship with the future as one of conquest rather than surrender.",
            "A Jedi is schooled in relinquishment, Anakin has never once relinquished anything, and his vow that he \"won't let this one become true\" is possession disguised in the vocabulary of love.",
            "Hamartia - The Tyranny of Devotion Aristotle’s Hamartia works not as vice but as frailty, an imperfection indigenous to the hero’s own nature, a not imposed on him from without. In Anakin, this frailty takes the shape of love so absolute it cannot tolerate the ordinary erosions of mortality, wedded to a conviction that sufficient will can bend even fate to heel.",
            "Aayush S. B. | IB II Yr Aristotle held that the most devastating reversals are those the hero unknowingly manufactures himself. Anakin's Peripeteia arrives in the Chancellor's chambers, where he enters believing himself the exposer of treachery and departs its instrument. His plea to Mace Windu that Palpatine be tried, not executed, is in itself the hamartia made manifest in its purest form: the same desperate insistence that the universe yield to his terms rather than its own.",
            "In striking down Windu, Anakin does not so much fall as continue, the gesture is not what most believe as rupture, but culmination, the tragic logic in which catastrophe emerges organically from character rather than intruding upon it. Every act that follows, the kneeling before his new master, the extinguishing of the Temple, unfolds with the merciless coherence tragedy demands, that which being, inevitability legible only in retrospect.",
            "Anagnorisis - The Ash of Anakin’s anagnorisis arrives as nothing but ash. On Mustafar, confronted by Padmé's horror, he answers with the knife of accusation, rather than clarity. Obi-Wan, he insists, has turned her against him, a sentence that reveals the absolute absence of knowledge, a man narrating his ruin as persecution. True recognition is delayed until he lies mutilated upon the volcanic shore, his voice dissolving into a scream directed at the man who defeated him. This too yet fails as wisdom, barely at its threshold, the first dim apprehension of an irony too exquisite to be coincidence: the vision he tortured himself to avert, he alone brought into being.",
            "Aristotle believed tragedy should leave its witness trembling with Eleos and Phobos in equal measure; pity for the one who falls, and dread at the narrowness of the distance between his fall and one's own. It is this second current that popular memory has long declined to feel, for Anakin's flaw is neither exotic nor alien; it is love disfigured by the fear of its own impermanence, the seductive and universal delusion that longing, sufficiently fierce, might compel the world into submission.",
            "Few who have felt this impulse become Vader. But the mechanical exhalation that closes the film, supplanting forever the voice that carried three pictures, is not the sound of a monster's birth. It is the sound of an entirely human hunger having consumed the vessel that once contained it, and it is in this recognition, rather than in spectacle, that the prequels finally earn the name they were so long denied: tragedy, in the oldest and most exacting sense of the word.",
        ],
    },
    {
        "slug": "is-ai-art-really-art",
        "title": "Is AI - Art Really Art?",
        "issue": 31,
        "date": "May 2026",
        "author": "T.Muhil | IB 1 Year",
        "section": "Opinion",
        "excerpt": "In today’s world, nearly everything we do has a trace of artificial intelligence in it, from our daily tasks to our school projects.",
        "paragraphs": [
            "In today’s world, nearly everything we do has a trace of artificial intelligence in it, from our daily tasks to our school projects. Even solving a simple math problem leads to verification from AI. We have become habituated to using AI in even the smallest things possible, so much so that it has become an inseparable part of our lives. Not to forget some countries have AI bots as their ministers! AI has recently also invaded the sphere of art in , stealing jobs of several digital artists and content creators. According to a survey conducted by the Society of Authors, about 26% of freelance artists lost their income because of AI.",
            "This intervention of AI in the domain of art raises a peculiar question - Is AIgenerated art really art? To answer this question we need to travel back in time to when traditional artists thrived. Art is considered the mirror of a society, defining the characteristics of the human species, serving as a universal language that has recorded human experiences, values, and emotions for tens of thousands of years. Throughout history, it has functioned not merely as decoration, but as a crucial tool for rituals, communication, social status, and historical documentation.",
            "Even today art is valued at millions and is considered a symbol of status. An artist takes hours painting each stroke, constructing his painting with absolute precision, each painting carrying his emotions within it. Each painting whispers a thousand untold tales. But that is not the case anymore when we humans started using AI to generate art, we eradicated the very purpose of art. AI is a mere algorithm made to save our time and make our work efficient, but it has become so paradoxical that it started eating up the unique element that defined us humans for what we are - our mind.",
            "Within a decade, we might not have the same crowd navigating to the galleries of the Louvre to admire the mastery of the Mona Lisa as we lose this beautiful bond between a human and a brush. Our appreciation for true human art has reduced as we’ve start shifting to more AIgenerated, lifeless art forms. The coming generations might not even know what Tanjore painting is! We are letting algorithmic efficiency take over the beauty of authentic human expression. This is a clear sign of our humanity itself deteriorating.",
            "Unlike an artist who creates from his own lived experiences, from joy, sadness, anger, AI generates mirrors of existing patterns and data. It doesn’t have the same emotional attachment to the shallow art it makes. Art becomes beautiful when it has the human touch of imperfection, not when AI simply converts ‘art’ into a simple program that places pixels in the right way to make a ‘perfect’ version of the image. Let us make this clear - AI is a mere tool that should assist us with our day to day activities, we must not allow it to become a thief that robs our jobs, and more importantly, our thinking. Art without its human touch, ceases to be art.",
        ],
    },
    {
        "slug": "rumors-at-cirs",
        "title": "Rumors at CIRS",
        "issue": 31,
        "date": "May 2026",
        "author": "Aarav Bhartia | IB 1 Year",
        "section": "Campus Life",
        "image": "rumors-at-cirs.webp",
        "image_alt": "Illustration of one person whispering to another",
        "image_width": 1983,
        "image_height": 793,
        "image_caption": "Illustration supplied for the web edition.",
        "excerpt": "Do you agree with me that here, in CIRS, news about people and events spreads like wildfire? Whether in late-night talks or Crossroads walks, we cannot keep gossip to ourselves.",
        "paragraphs": [
            "Do you agree with me that here, in CIRS, news about people and events spreads like wildfire? Whether in late-night talks or Crossroads walks, we cannot keep gossip to ourselves. We all have the desire to tell someone about that one person or that one ‘kaand’ which we found out about from somewhere. Everyone wants to be the one who knows stuff and the one who reveals it. But imagine this: you tell something about yourself to some of your close friends, and the next day, every single person knows about it. Have you ever experienced this in CIRS?",
            "It is very important to understand the impact these rumors can create on victims of these whispers. Rumors must be handled very carefully because they can either make a failure look like a hero or destroy a person’s hardearned reputation. Can you imagine if something completely fake about you has become a hot topic for the school to gossip about? Can you imagine how that person would be struggling every single day to change everyone’s wrong perception about him?",
            "During the process of spreading news, or what we can call “gossip,” something very interesting happens. This passing of gossip becomes like the game of Chinese Whisper. The first person, who gets the information from the primary source, tells it to the second person. Now, the second person hears something, comprehends it differently, and then passes it on to the third person as something entirely new! When this cycle continues through a long chain of people, the news gets altered and modified so much that it becomes completely different from what it originally was. This is when the ‘news’ becomes a ‘rumor’.",
            "- The Epic Choice Now the question arises: why do people even spread rumors in the first place? Usually, they make assumptions about a person or an event from the news they hear. Or, they are simply jealous of the other person’s success or achievements and try to pull them down by spreading a rumor. If we are among these people, then we must reflect and ask ourselves some questions- Is spreading rumors or gossiping about people in any way conducive to me? Is it ethical to create a fake black mark on someone’s hard-earned reputation? Am I letting my anger and hatred control my actions? Is it going to benefit the collective society?",
            "When you answer these questions, you will realize whether you should be encouraging gossip or not. If we get some information about someone or some event, then before telling others, we must confirm it with the original source. In fact, why should we entertain gossip? It is a mere waste of time. There are better things to do in life. Remember, today when you gossip and spread rumors about someone; tomorrow it might be your turn.",
            "ITIHASA - The Epic Choice To me, acting was always somewhat a decently tough job, made for those who can easily understand others. Having barely acted before - and even so only in roles which relate to real life - I never really understood the pain involved and control required for this phenomenal yet tedious task. Receiving the role of Duryodhana as my first major role was exciting and scary.",
            "Mostly scared, as every time I tried something or acted in a certain manner, it just did not work out. A week of practice passed and I still faced a jittery body, expressionless or overemotional actions, and disappointed incharges dictating my work. And, by some divine intervention, my role in the play came out really well. Although it sounds like happenstance, what I learnt from this role was so much more impactful.",
            "Persistent effort and focusing solely on a goal actually makes a change. The late nights and the early mornings proved to me that hard work without complaint truly shows results, even if it seemed hopeless early on. To become someone or something, the mind should already pretend and behave as such, before the body can begin reaching that state; which, in this case, is to actually be Duryodhana a week prior to my acting as Duryodhana.",
            "This applies for any role, be it something noble, or something villainous. Lastly, I understood the importance of time management. Managing studies, practice for the upcoming tournaments, daily habits and the acting practice opened to me the vast realm of possibility, fueled only by the amount of effort and management put into it. I’m merely on the first step of a long journey. Chucking the small, unwanted things is where the secret of it all lies!",
        ],
    },
    {
        "slug": "hot-wheels-vs-barbie",
        "title": "Hot Wheels V/S Barbie",
        "issue": 31,
        "date": "May 2026",
        "author": "Prisha Kantesaria | IB II Year",
        "section": "Opinion",
        "image": "hot-wheels-vs-barbie.webp",
        "image_alt": "Hot Wheels cars and track beside a Barbie doll",
        "image_width": 1536,
        "image_height": 1024,
        "image_caption": "Illustration supplied for the web edition.",
        "excerpt": "I am a proud biology student, and my biology class has a MEGA, WHOPPING, GARGANTUAN class strength of 2! And these supercalifragilisticexpialidocious students are girls.",
        "paragraphs": [
            "I am a proud biology student, and my biology class has a MEGA, WHOPPING, GARGANTUAN class strength of 2! And these supercalifragilisticexpialidocious students are girls. ‘Bio students, then they’re definitely going to be girls.’ That would have certainly been your first thought too! But if I talk about a big-shot neurosurgeon - most of us are instinctively going to presume that he is a man, a tall, hefty male who can cure your brain tumor by simply looking at you.",
            "We can’t really put anyone to blame here. This system has been with us since Day 1: it grew with us and within us, and got entwined in our tiny little brainboxes. From the beginning, spatial awareness toys like ‘Lego’ and ‘Hot Wheels’ have been marketed to boys and empathy-based toys like ‘Barbies’ and ‘Dollhouses’ go to the girls. This doesn’t mean that we entirely stop giving Barbies to girls and cars to boys.",
            "The majority still prefers it that way. If someone would’ve attempted to take kid Prisha’s Barbie doll away from her, she would’ve definitely strangled them with bare Barbie hands. Yet, somewhere, she was also always a teeny bit jealous of her brother getting the coolest, craziest, most exhilarating race tracks and transformers all the time. So now the question arises, what should kids like Prisha do? They love their Barbies, but also want to race a 1969 Pink Rear-Loading Beach Bomb or a Bone Shaker (for those of you who don’t know these are Hotwheels) on the twisty orange track. Do they fall prey to the cognitive comfort zones created by the system?",
            "So what to do now? Kid Prisha’s problem becomes adult Prisha’s problem too! And let’s not just limit this complication to the ladies. Somewhere, some XY-chromosomed Paresh would also be subjected to the same hitch. Is blaming the system going to reshape the system? The only thing one can do here is go after what they truly desire and strive to achieve it. A prime example of such a system reshaper lives right with us, our very own Bhakti Didi!",
            "During her Vedanta course, Didi was the only female in her batch. The only lady, amidst 17 men. She did it. She did her part in refusing to let the system change her future. And her story urges us to contribute in redefining it.",
            "Pitifully, yes. This ‘system’ continues to affect subjects like teens and even perpetuates to adults deciding on jobs. Research shows that when a large number of women enter a field, the average pay tends to stagnate or drop. Disconcertingly, when a male enters such a field, he often gets promoted to management roles faster than his female co-workers. This brings us to the Pollution Theory. Sociologists believe that the presence of a marginalized group ‘pollutes’ the prestige of the domain for the dominant group, prompting ‘men’ the ‘dominant group’ to split away from it, merely to preserve their social standing.",
            "Ideally no field should just have Shiva or Shakti. A surgeon needs the technical precision of Shiva and the healing nature of Shakti. A software developer needs the logical nature of Shiva and the user-centric approach of Shakti. Gender bias forces people to suppress the other half of their nature. A society where men are encouraged to embrace their Shakti and women are empowered to express their Shiva is a society that operates at utmost proficiency.",
            "Women’s professional skills are often dismissed as natural traits whilst that of men are considered as expert specialization. The most fitting example would be that of a chef, where at times gender eclipses talent, leading to massive pay gaps.",
            "This brings us back to the system. The extremely misconstrued and misconceived system. Its original essence has been diluted through centuries of faulty interpretation. We come from a heritage so vast, philosophies so profound, culture which venerates Shiva-Shakti … The Ardhnarishwar. The entire concept of Ardhnarishwar is based on the interweaving of both masculine and feminine energies. Shiva represents consciousness (structure and logic), while Shakti represents energy (creativity and care).",
            "Prisha Kantesaria | IB II Year So, instead of baselessly arguing that women should also do every single job, one should consider the biological sciences that once built this occupational framework. While equal rights and equal wages are necessary, it is crucial to understand the necessity for certain gender based divisions in specific fields, based on the genders’ specializations and limitations. Some fields require a predominant Shiva energy, while others thrive in the force of Shakti.",
            "The right career trajectory is adhering to these biological predispositions while parallely prompting individuals to look beyond senseless restrictions, to embrace their Shiva-Shakti and to chase even their most ‘implausible’ desires - be it Barbies or Hot Wheels.",
        ],
    },
    {
        "slug": "geography-and-geopolitics",
        "title": "Geography and Geopolitics",
        "issue": 31,
        "date": "May 2026",
        "author": "Shaurya Bhartia | 12 Mgmt",
        "section": "World",
        "image": "geography-and-geopolitics.webp",
        "image_alt": "Hands moving chess pieces across a map of the world, illustrating geopolitical strategy",
        "image_width": 1024,
        "image_height": 572,
        "excerpt": "Every week, we stare at the \"News of the Week\" presentation on the screen, clapping loudly at the second anything mildly related to India, any sports team, or Donald Trump that flashes by.",
        "paragraphs": [
            "Every week, we stare at the \"News of the Week\" presentation on the screen, clapping loudly at the second anything mildly related to India, any sports team, or Donald Trump that flashes by. But have you ever tried to understand what’s actually going on behind those headlines? Or are you content with just having the worldview of a goldfish, only noticing whatever gets dropped into your bowl?",
            "Daily newspapers and that weekly presentation are our main windows to the outside world. But reading the news and understanding the world are two very different things.",
            "The problem is we only look at problems at their surfacewho won, who lost, who launched a missile. But global politics isn't a culmination of random moves around the world. Every move is a massive, multiplayer, carefully structured chess game that is dictated by a very stringent strategy book.",
            "To actually understand this game, we need to stop staring at the players and start looking at the board itself. First, you need to understand what lies at the very base that forms its structure. It’s rivers. Mountains that surround it. Because in geopolitics, the map is the script. If you have been going through the newspapers anytime during the last 2 years, you would have recognized that Russian tanks are rolling into Ukraine, and Indian and Chinese soldiers are in tense standoffs in the Himalayas.",
            "On the surface, these look like two entirely different conflicts driven by different politicians. But if you strip away the speeches and look at the maps, both of these situations are driven by deep, geographically rooted motives.",
            "First, we will move to Russia’s nightmare. Despite its monstrous size, most of Russia’s northern ports on the Arctic freeze over every winter. This cuts Russia off from a substantial amount of trade, and this also makes Russia vulnerable to naval attacks. To continue being a global superpower, Russia must have a \"warm-water port\" so its trade ships and navy can sail year-round. So why Ukraine? What's the prize? Simply put, it’s the port of Sevastopol located in Crimea on the Black Sea.",
            "If Ukraine permanently allies with the West, Russia risks losing its only reliable, year-round door to the Mediterranean Sea and, consequently, the rest of the world's oceans. Russia's invasion isn't just about grabbing land: it’s a desperate fight because they are geographically imprisoned. They need that port to survive as a global superpower.",
            "Shaurya Bhartia | 12 Mgmt Now let's go south on the world map, and look at the India-China border. Here, nature manifested differently: it fortified India with the most magnanimous fortress, the Himalayas.",
            "Since these mountains are so massive, a traditional, large-scale tank invasion between India and China is practically impossible. So why the tension? Because in this game, whoever controls the high ground controls the ultimate resource: water. China occupies Tibet, known as the Water Tower of Asia, and the starting point of rivers that quench an entire continent’s thirst. India’s geographic anxiety is that if China controls the peaks, it controls the water source. Now look at the contrast between the two - Russia fights because it is trapped by ice. India and China clash because their maps are too high.",
            "The best part about this rule is that it applies everywhere, directly or indirectly. Once you learn how to read the map, the whole world starts to make sense.",
            "For a real-time example of geographic leverage, look at the Strait of Hormuz. This tiny, 21-mile ocean gap controls roughly 20% of the world's daily oil transport. It is the ultimate choke point, exhibiting how a country like Iran can use a gap in the map to hold a global superpower hostage.",
            "Why hasn't China simply invaded Taiwan? The US Navy is not the only limiting factor - it's also the map. To attack, China has to cross over 100 miles of brutal ocean (the Taiwan Strait) and land on a heavily layered, mountainous island with only a few muddy beaches. Geography makes it the hardest military to infiltrate in modern history.",
            "Ever wonder why some resource-rich African nations struggle with trade to date? Their massive rivers frequently transform high plateaus into steep waterfalls, making it physically impossible to sail cargo ships inland. Transport is thus done through the shores, making the prices hike steeply.",
            "These aren't just fun trivia: they are the invisible rules of the metaphorical chessboard. Every headline flashing on the screen is just the latest move on a board that was shaped eons ago.",
            "Since we don't have internet access during the day to instantly Google the backstory of every headline, we have to use our heads. This week, pick just ONE international conflict from the newspaper in the common room or from the \"News of the Week\" on Saturday.",
            "Instead of just accepting what happened, go find an atlas or a map in the library. Look at the terrain where the headline is taking place. Is there a river? A mountain range? A narrow gap of sea? Ask yourself: If this mountain or river weren’t here, would these two countries still be fighting? Don't assume and create your own inferences from it; make sure you put forth the practicality of that being the motive before concluding.",
            "It's time to stop simply watching the news and start reading the map.",
        ],
    },
    {
        "slug": "sportswashing",
        "title": "Sportswashing: The New Geopolitics",
        "issue": 30,
        "date": "April 2026",
        "author": "Shaurya Bhartia | XII MGMT",
        "section": "Sport",
        "excerpt": "The summer of 2023 changed football forever. It wasn’t just the usual go-to of European transfers; it was something weird. Why?",
        "paragraphs": [
            "The summer of 2023 changed football forever. It wasn’t just the usual go-to of European transfers; it was something weird. Why? When Cristiano Ronaldo moved to Al-Nassr, many dismissed it as a career-ending move. But then came other big names: Neymar. Sadio Mané. Firmino. Maharez. Saint-Maximin. And then the Ballon d'Or favorite, Karim Benzema. These players were all at the peak of their careers. Suddenly, the Saudi Pro League wasn't just a retirement home, it was a glitch in the transfer market.",
            "As a Liverpool fan, seeing club captain Jordan Henderson or Fabinho depart for the Middle East after a monstrous season felt odd. But to understand why this happened, we have to look past this season alone. We have to look at the real referee of global power: Geopolitics. This isn't just about football, it's about a concept called ‘Sportswashing.’ Sportswashing is ‘the practice of a nation, corporation, or individual using the prestige and emotional pull of sports to improve a tarnished reputation or distract from political controversy.’ A simple definition.",
            "But not-so-simple impacts. The logic behind this is very simple: it is much harder to criticize a country’s human rights record or its lack of democratic freedom when you are cheering for a 90thminute winner by a player they bought for your team or when you are cheering for the F1 races hosted in their country. Soon unintentionally, you become emotionally attached to the country .",
            "Saudi Arabia has generated enormous amounts of money from selling oil, but has a poor reputation regarding human rights, women’s rights, religious fundamentalism, and slavery. The government has been accused of supporting terrorism, bombing school buses full of children, and even killing U.S.-based journalists in their embassies. By spending billions on Cristiano Ronaldo, LIV Golf, and the 2034 World Cup, they are buying their way into a clean reputation, to distract us from these human rights records. This strategy creates a historical mirror, stretching from the 1936 Olympics in Nazi Germany to Saudi Arabia’s hosting of the 2023 Club World Cup.",
            "THE TRUTH THE TRUTH A TROPHY Shaurya Bhartia | XII MGMT In football we often talk about ‘club takeovers,’ but in reality, Western sports organisations like the PGA and debt-heavy football clubs are begging for Saudi capital to survive. By providing this rescue money Saudi Arabia isn't just buying a club or a tour, they are buying veto power over Western cultural institutions and into our subconscious mind.",
            "To understand the Saudi ideology, we must talk about Vision 2030, the brainchild of Crown Prince Mohammed bin Salman. This plan is centred around the Crown Prince's goal of turning his country into one that can survive – post the end of its petroeconomy. To do well, he needs us to buy into his vision, which is difficult when the world associates his regime with a brutal dictatorship similar to North Korea.",
            "This isn't just about global PR, it is also about internal stability. Sixty-three percent of the Saudi population is under the age of 30. Providing them with hardcore sports, like F1 or the FIFA World Cup, offers a distraction to keep their minds off major issues like unemployment, tethering their interests to state-controlled sports instead. This is what Saudi wants their ideal youth to be like. And this is not something which has been brought on by Saudi Arabia as a new project: it has been carried out by different countries for decades.This isn't just about global PR, it is also about internal stability.",
            "Sixty-three percent of the Saudi population is under the age of 30. Providing them with hardcore sports like F1 or the FIFA World Cup, offers an anchor to keep their minds off major issues like unemployment, tethering their interests to state-controlled sports instead.",
            "This is what Saudi wants their ideal youth to be like. It is a strategic trade, “We give you the world’s best entertainment; you give us political stability.” And this is not something which has been brought on by Saudi as a new project: it has been carried out by different countries through decades: -Benito Mussolini’s Italy: used the 1934 FIFA World Cup to defend their fascist disciplinarian projects.",
            "-1936 Berlin Olympics: Nazi Germany used the Games to project a facade of a peaceful, tolerant nation while internally accelerating the holocaust.",
            "-1980 Moscow Olympics: The Soviet Union conducted the Games to showcase communist superiority and global influence right after their invasion of Afghanistan.",
            "-2014 Sochi Winter Olympics: Russia spent a record $50 billion to project national prestige, only to launch the annexation of Crimea just weeks after the closing ceremony.",
            "-The 2014 Sochi Olympics, The 2022 FIFA World Cup, the list goes on.",
            "-2022 FIFA World Cup: Qatar spent an estimated $220 billion on infrastructure to distract nations from its treatment of migrant laborers.",
            "-The 2026 FIFA World Cup: USA is showcasing a narrative of national unity, masking the reality of extreme political polarization, record-high baseless deportation rates and lack of due processes.",
            "In 2017, just as the nation was warming up for the tenth season of IPL the Finance Bill was passed just as a \"Money Bill,\" quietly merging 19 tribunals and making Aadhaar mandatory By classifying this bill as a Money Bill, the government effectively bypassed the opposition of the Rajya Sabha, allowing widely controversial shifts such as removing caps on corporate political funding to pass with minimal public scrutiny while the public was obliviously anchored to the pitch. This has the potential to make our government indebted to private organisations without us every knowing.",
            "Fast forward to last week; as RCB faced SRH, a Special Session was convened to fast-track the Constitution (131st Amendment) Bill and the Delimitation Bill. Aimed at putting into practice the 2023 Nari Shakti Vandan Adhiniyam for the 2029 elections, the amendment sensationally fell short of the required two-thirds majority in the Lok Sabha.Upon closer inspection, I've realised that these controversial Special Sessions are scheduled to coincide precisely with these IPL matches. This ensures that while the attention of fans is glued on the final overs, the country can be presented with fundamental changes that have the potential to alter the very things that we stand for.",
            "Ultimately, we must realize that every boundary shot and goal cheered for is a distraction. Whether in Riyadh or New Delhi, this is what we see everyday around us, yet fail to notice how r every small move made right in front of our eyes, has a much bigger play to it on the geopolitical arena.",
        ],
    },
    {
        "slug": "notes-of-healing",
        "title": "Notes of Healing",
        "issue": 30,
        "date": "April 2026",
        "author": "Ishaan Ravishankar | XII MGMT",
        "section": "Culture",
        "image": "notes-of-healing.webp",
        "image_alt": "Guitar, headphones and records beside an open notebook",
        "image_width": 1536,
        "image_height": 1024,
        "image_caption": "Illustration supplied for the web edition.",
        "excerpt": "Music is something most of us cherish, holding a special place in our lives. It speaks volumes about our personality, and offers insights into our very souls.",
        "paragraphs": [
            "Music is something most of us cherish, holding a special place in our lives. It speaks volumes about our personality, and offers insights into our very souls. So why is listening to music so gratifying? Why does it hold so much power over our minds, influencing even our emotions? What is it about random combinations of sounds put together that leave such a striking impression?",
            "Music has the ability to bring us joy and comfort, it motivates us and helps us relax. It has the power to transport us back to our happy places, calming our frenzied minds. On the other hand, this tricky tool has the ability to produce the most tense and coldest of emotions. This effect is best seen in the blockbuster Interstellar (2014). The scores composed bring out the most intense versions of tension and despair, making the audience squirm in their seats.",
            "Music has always been a powerful way of communicating. Music helps provide social and cultural identities to people. Music has the power to unite, inspire, and change the experiences we undergo. For example, National anthems connect crowds at sporting events, sacred hymns build group identity in religious gatherings and the occasional neighbourhood band fosters collectiveness and teamwork.",
            "Music psychology, a branch under the wide study of Musicology, is a field of study diving into the science of the dimensions displayed by music by searching through the human brain for answers on how humans perceive, respond and interact with music. It explores the relationship between human behaviour and emotion while composing music, playing instruments or even singing your heart out. It aims to understand how people experience music and how in turn music affects behavior. The study of music psychology also helps researchers understand the differences and effects of music in different cultures.",
            "This application of musicology is very versatile, extending to various fields of study ranging from performance psychology - helping professional athletes train, to the use of music to enhance the concentration of surgeons, where music is played at specific tempos to enhance performance and maintain stability.",
            "One of the most well-known uses of music psychology is Music Therapy, wherein music is used to cure ailments, both mental and physical. Researchers have determined that music can soothe upset people, motivate those in need of encouragement, and affect emotions in various other ways. Music therapists use this knowledge to prescribe certain music to help those with certain mental and cognitive health issues. For example, a music therapist working with a patient with post-traumatic stress disorder (PTSD) might recommend the use of classical music to help the patient remain calm, while upbeat music can thwart motion sickness and nausea.",
            "This form of therapy has been tried and tested on countless occasions, producing results that stun medical professionals, abbreviating diseases once said to be incurable. It has proven to improve cognition for patients with conditions like Retrograde Amnesia, Dementia, Alzheimer's and other autoimmune diseases with just some music that associates the patient with meaningful memories. Music can help retain essential information despite the above diseases. ‘Music memory’ is stored in the hippocampus, located in the centre of the brain.",
            "Therefore, music memories are less likely to be negatively impacted by age or disease. It also demonstrates the effect of music on speech and language, curing stuttering and linguistic disorders. Because music is often an enjoyable activity, it can activate the release of endorphins, which creates a general feeling of well-being. Music therapy can successfully reduce post-operative pain, physical tension and influence heart and breathing rates. Fast music tends to increase pulse rate and blood pressure.",
            "Slow music tends to decrease pulse rate and blood pressure, as well as breathing rate. This technique is used for patients posted in Intensive Care Units to support recovery. Music has a profound influence on health, culture and society. Its power to sway us to its tunes is truly marvelous. Music psychology demonstrates that music is much more than entertainment by scientifically analysing the human brain and its responses to music.",
            "Its applications extend far beyond leisurely listening, helping professionals enhance focus, endurance and stability. Every tune transforms you, every rhythm changes you, and every melody modifies you.",
        ],
    },
    {
        "slug": "my-home",
        "title": "My Home",
        "subtitle": "A place where you are always welcome and surrounded by those who love you",
        "issue": 29,
        "date": "February 2026",
        "author": "Vishv Prem Nangia",
        "credit_source": "site",
        "section": "The Editorial",
        "excerpt": "Like most other kids, I had an enjoyable childhood with my family, so naturally, making the tough decision to join a boarding school 2,359 long kilometres away from home was an emotional one.",
        "paragraphs": [
            "Like most other kids, I had an enjoyable childhood with my family, so naturally, making the tough decision to join a boarding school 2,359 long kilometres away from home was an emotional one. But by fate or by chance, I landed at CIRS in 2022 after almost a year of online classes due to the pandemic, and since then, I've had quite the experience of a lifetime.",
            "Joining in 6th grade as a shy young boy who played too much Minecraft and coming to a beautiful campus filled with so many other boys and girls my age hailing from all over the country and world, whom I would literally have to live with 24 hours a day, 7 days a week for the majority of each year, was an experience like no other. Some would argue that it's the best part of a boarding school - the friends you make and the family you learn to live with.",
            "Fast forward 4 years, and now that my journey is nearing its end, I can't help but remember all the good times I've had, from the weekly pleasure of paneer and the bustling economies that thrive with it, to the Sunday morning Yuvakendra classes. From my liberal and romantic encounter with the rules and regulations to the joy of fast-paced quizzing for the school team, from the light-hearted moments on the tennis court to the heavier ones in the last few nights before Anand Utsav. From the innocence of Govindalaya, the laughter of Krishnalaya, and the love of Keshavalaya to the home I've found in the prime real estate of the office.",
            "Above all, I feel the best part about this school is the abundant opportunities given to all who are willing to take them. The opportunity to be stronger and faster, gain more experience, participate in and perform in competitions, sports, quizzes, debates, and so on. But the most unique opportunity, and arguably the one that matters the most, is the opportunity to become spiritually strong, patriotic, and culturally grounded. This is a school run on the values and the vision of Gurudev by his followers, and after joining here, I've become more aware of the glorious past of this nation and more patriotic towards its promise of the future, and that has made me a more genuine and better person than I was to begin with. And for that, I will forever be grateful to this school.",
            "At the end of the day, the rising sun must set at dusk, for the golden dawn of tomorrow. I understand that this journey has come to an end, and that all that is left to do is embrace its course and keep it in my heart as I go. I've come to terms with the fact that I'll be packed and boarded back to Gurugram for the last time as a student on the 10th of March, and I'm beginning to realize how much I'm going to miss my second home, the beautiful hills (that I hoped to climb), the unique excellence of our Annakshetra, the worn tiles of the crossroads, the dorm rooms, the wilderness of the C-sectioned classrooms, the charm of the tennis court, the clean air, the cool pool, the dusty tracks, and of course, the people that bore me through 5 years.",
            "A school is beyond its mere infrastructure, and becomes a home to so many people because of everyone who studies, teaches, and stays there. And to all of them, my teachers, mentors, dorm parents and friends I am forever grateful. Thank you!",
        ],
    },
    {
        "slug": "voyages-in-the-yuva-kendra",
        "title": "Voyages in the Yuva Kendra",
        "subtitle": "A memoir of my brief experiences in the shadow of Gurudev’s light for the youth.",
        "issue": 29,
        "date": "February 2026",
        "author": "Adithyan Diwakar Vidya | Class IB II | CIRS",
        "section": "Reflection",
        "image": "voyages-in-the-yuva-kendra.webp",
        "image_alt": "Large group posed together outside a building",
        "image_width": 681,
        "image_height": 453,
        "image_caption": "Group photograph supplied for the web edition.",
        "excerpt": "Bag stuffed, folder filled, and brain completely devoid of meaning: that would accurately encapsulate my state in the very first class of CHYK CIRS.",
        "paragraphs": [
            "Bag stuffed, folder filled, and brain completely devoid of meaning: that would accurately encapsulate my state in the very first class of CHYK CIRS. Seated in a circle with faces familiar and unfamiliar, I felt more apprehension than inspiration. And yet, here I find myself three years on, molded by the hands of giants, in the service of the God called Man, with my eyes blissfully opened to the infinite potential in all things living.",
            "This was no instant transformation. At first glance, the Chinmaya Yuva Kendra at CIRS was only a tangled mass of philosophical sessions, with perhaps a few outings filled with exciting activities and performances in between. But as we turned the pages of 'Freedom and Licence,' the first chapter of our study, Gurudev's words seemed to leap out of the pages and into the core of our hearts. I felt an indescribable weight in them, jolting me to move beyond mere intellectual wanderings into living and breathing spirituality.",
            "There exists a gross misconception of spirituality, that it is only a field for the old and decrepit folk, living out their days in solitude and isolation. CHYK showed me the polar opposite - a gathering of young people constantly chipping away to mold their character, building themselves to build Bharat. Their infectious dynamism proved to me that spirituality is no secluded field. In fact, it is not a field at all, because it deals instead with the one commonality that threads together all fields of the world: your Self.",
            "There exists a gap between good and bad, a chasm between the righteous and the ignoble. Every student feels the strong tug of the latter side, egging them on to settle for lesser, the more appealing and pleasurable. I certainly did. But self-control is not the absence of temptation; it is one's triumph over it.",
            "My greatest battles were not blind competitions for marks with my peers or my struggles on the sports field - they were in quiet moments in the dead of night - warring against my own mind. And while I had several companions in my other endeavors, my sole pillar in this inward fight was CHYK. CIRS offers us two paths - one of industrious work, dedicated effort and unwavering character, and another of wasteful lethargy, impermanent joys, and low-quality living. Our unfortunate reality is that the first path is a road not taken, while the second sees several travellers with each passing moment.",
            "My own path-changer was a single habit; the Yuva Kendra's greatest gift to me: Sadhana. Simply chanting a set of 24 syllables might seem like the most mundane activity on this planet, and yet a mere 108 turns of my mala beads every day have brought quietude to my once-wayward mind. It has imparted to me a strength unspeakable: one that allows me to take a stand against hundreds and thousands without batting an eye.",
            "It has hardened me to become immune to any challenge, trouble or tribulation that the world may throw at me, and it has also softened me to withdraw the venomous hatred that I once used to throw out into the world. CHYK's activities are not unlike those at several other schools: light-and-sound shows, school-wide yatras with interactive stations, temple treks, and the foundational weekly classes are nothing outside the perceived normal.",
            "But I soon discovered that CHYK's real beauty lay not in its activities, but in the spirit with which they were executed. The determined ideation, enthusiastic execution, and whole-hearted servitude pushed me to constantly, joyously serve the Yuva Kendra. In return, it gave me perhaps even more: it took me across Bharat to the International Youth Convention, placed an entire cohort of aspiring Chyksters in my hands, and brought my words to thousands of people through the Chinmaya Udghosh.",
            "Slowly, silently, the months of sadhana, study and reflection piled on top of each other to bring about a revolution from within. I feared less and cared more. I talked less and worked more. I fought less and thought more. I cannot pinpoint exactly where or when these changes came about. I can only stand today on the shore, look back at the raging storm, and bow in gratitude to the organization that sailed me through it.",
            "I know still that I have accomplished nothing - that there are many more mountains to climb, and many more storms to weather. But the Yuva Kendra has brought me some part of the way up the highest peak - the peak of self-mastery - and so I know that the challenges of the world, no matter how large they may seem, are never insurmountable.",
            "To all those who wish to truly join CHYK: leave your ego at the doorstep, open up narrowed notions and embrace these teachings with pure love and unwavering faith. Question everything. Hate nothing. Reflect daily. Speak boldly. Act powerfully. Slowly, you will find yourself staring back and wondering what magical touch must have taken place to turn you into the person you will be. That is no magic. It is transformation - slow, strenuous, and unfathomably rewarding.",
            "It is the hallmark of this organisation. Yuva Kendra is not a place for the spineless. Its first principle is that spirituality is about lived experience, never about purposeless discussion. I have made difficult choices, sometimes excruciatingly painful ones, but behind every choice is the call of dharma - of that unfailing righteousness that separates the mighty from the millions.",
            "Somewhere far along this journey you may catch a glimpse of God, and beyond that there is nothing more I can tell you about - only an existence so beautiful that describing it would be defacing it. You will find Him, not with a great white beard in the clouds, but shining through every man, woman and child around you. That is a faraway summit, but we can begin today with a choice - the Yuva Kendra choice - of slowly removing that vile selfishness from ourselves and growing into more successful individuals in the service of noble causes. Until that day, my humble farewell.",
        ],
    },
    {
        "slug": "the-race-beyond",
        "title": "The Race Beyond",
        "issue": 29,
        "date": "February 2026",
        "author": "Lokk Vishwavedaa",
        "credit_source": "site",
        "section": "Economics",
        "image": "the-race-beyond.webp",
        "image_alt": "Rear view of a Formula 1 car silhouetted against a fiery sunset sky",
        "image_width": 2236,
        "image_height": 703,
        "excerpt": "It's Sunday. Millions are tuning into their digital screens to watch one thing. Fast cars. Actually, 20 of them, racing at speeds that vaporize everything in their path.",
        "paragraphs": [
            "It's Sunday. Millions are tuning into their digital screens to watch one thing. Fast cars. Actually, 20 of them, racing at speeds that vaporize everything in their path. Behind their wheels lies the brave racer, experiencing the rush. All for one cause. Pass the checkered flag first. For 2 hours, engines scream, tires burn, and the world witnesses pure acceleration. For most, F1 ends there. The Pinnacle of Speed, Motorsport.",
            "A simple race. But wars are not fought in press meets and are not won in TV interviews. Beneath the glamor and the rush exists a system where the $$$ dictates performance, existence and survival. Three years ago F1 generated over $3.4 billion in revenue. Mind you that is a figure which can fund a small nation for 365 days. F1 is not just a mere motorsport, it is an economic machine.",
            "Money enters F1 through channels that are specifically designed for control and predictability. The largest piece of this cake comes from the broadcast and the media rights. Companies are desperate over owning the rights to show F1. These rights are sold to various networks around the world, in safe, long term contracts. This is a failsafe that ensures no matter who the victor may be, the sport retains its money.",
            "Governments too pay a staggeringly huge amount to host these races, with the figure being around 30 to 60 million dollars. This price is paid by the governments as F1 offers many perks with them. It offers visibility, prestige and strong geo-political branding. Add to this huge capital injections from corporate sponsorships, buying association with the team with innovation and dominance, these streams manage to create the constant ever flowing capital into the sport.",
            "Beneath the roar of engines lies Formula One Management (FOM), the entity that truly commands the world of adrenaline. It owns the commercial rights, oversees and controls negotiations and easily decides who eats and who starves. It doesn't race, engineer or innovate, but this entity dictates the future of F1 motorsports. Its role is one of a Financial gatekeeper. The FOM collects tons of money and cleverly redistributes them selectively under the jurisdiction of the 'CONCORDE' agreement, while retaining its own benefits for its parent company, Liberty Media. This tells us that this is not competition. It is centralised, formalized, cold hard control. F1 exists as a monopoly.",
            "The teams delve into their sector, rounding up to the crucial question. \"How can I cross the checkered flag first?\" injecting millions into aerodynamics, simulations and clean, data driven, statistic based marginal gains. The engineers responsible for this are absolute assets. The commanders of the engine, the drivers, are commodities. The logistics by itself amounts to millions, with the teams shifting across the continents all year round. The induction of the cost cap was cleverly marketed as reform, but in reality, it barely slowed down the spending. This reform was unable to touch the decades of accumulated advantages.",
            "Outside the circuits, the F1 economy plunges into the national economies and the host countries observe massive boosts in their revenue due to tourism and active infrastructure betterment. The team owners reap their benefits. The payout system in F1 might seem unfair to most people, but in reality, the system is clear cut. The strongest and the fastest survive. The payments are based on the legacy of the wins and the team's current performance. The successful teams receive the \"Legacy Bonus.\" The sponsors increasingly gravitate to the dominant and the proven teams. This creates a feedback loop. Money produces performance, the performance attracts the money, and restart.",
            "While all of this is true, the public funds spent by the governments bear massive opportunity costs, which are ignored in this global race for recognition.",
            "So what is F1 really about? Is it about speed? About skill? Is it even about the competition? F1 is a closed, deep and beautifully detailed economic environment where the money is injected through the media deals and public funds, formalised under the FOM, redistributed to protect its dominance, while reinvesting to maintain the positions, and exported as global influence. The racing isn't fake. But the outcome is often decided before the lights go silent. Money not only rewards success, it actively manufactures it.",
            "So the next time you witness a system, don't stop at the surface-level details. Question it, observe it and then come up with your own thesis. The world is filled with puzzles to solve, and your mind is waiting for you to unlock them.",
            "See you in the next issue, with yet another Fiscal Narrative!",
        ],
    },
    {
        "slug": "trust-or-bust",
        "title": "Trust or Bust: The Never-Ending Problem of the Prisoner's Dilemma",
        "issue": 29,
        "date": "February 2026",
        "author": "Aarav Bhartia | X B",
        "credit_source": "school",
        "section": "Economics",
        "image": "trust-or-bust.webp",
        "image_alt": "Coca-Cola and Pepsi cans colliding",
        "image_width": 2172,
        "image_height": 724,
        "image_caption": "Illustration supplied for the web edition.",
        "excerpt": "Imagine yourself in this familiar high school scene where you and your best friend are tasked with a huge project, the kind that demands hours of focused, dedicated work.",
        "paragraphs": [
            "Imagine yourself in this familiar high school scene where you and your best friend are tasked with a huge project, the kind that demands hours of focused, dedicated work. Both of you want an A, but a tempting choice arises. Your friend is a highly motivated, driven student, capable of doing excellent work alone. This knowledge creates a loophole in your mind, a calculated bias that whispers: \"Why should I put in the full effort if I know my friend will carry the load anyway?\". This internal conflict between helping your teammate and prioritizing your own leisure is a situation quite common in classrooms, and is best understood through the concept of Game Theory.",
            "The basic conflict revolves around the choice between cooperation by doing your half of the work and defection by slacking off, hoping for a free ride. If both you and your friend choose to cooperate, you both work less and get an excellent grade - the desired outcome. But that tempting choice lingers - what if you defect? If your motivated friend still cooperates, you get the same excellent grade with zero effort. In pure rational terms, choosing defection seems like the most beneficial path for an individual. However, if both friends decide to be \"rational\" and defect, that is, assume that the other will do all the work, the project fails, and you both get a failing grade.",
            "The aforementioned situation demonstrates the core paradox about rational individuals making the best choice for themselves, while the collective outcome is often worse for everyone. This is an undervalued and rarely recognized concept, and can be seen in almost every situation where there is a dilemma. This concept of Game Theory is famously illustrated by the Prisoner's Dilemma, where two suspects are arrested for a crime and placed in separate rooms. They are each offered a choice: Either confess to committing the crime, or remain silent and refuse to cooperate.",
            "There can only be 4 outcomes:",
            "1. Both of the suspects remain silent, they each get a minor sentence due to lack of evidence - prison for 1 year.",
            "2. One of the suspects betrays the other, by confessing to the crime, and goes scot-free, while the other gets the maximum sentence of 20 years.",
            "3. Both of the suspects aim for betrayal, and confess - yet due to the honesty of both our criminals, they get a lesser sentence of 5 years each.",
            "Neither has any idea of what the other will say, and have no method of confirming what the other has said. Hence, without knowing the other's choice, the most rational and selfish strategy for an individual is to confess. This is the most cost-effective solution, regardless of the other suspect's choice. Either you get the best outcome of freedom, or the sub-optimal 5 year sentence. Naturally, a \"fair\" choice would be to both remain silent and get the minimum common punishment of 1 year, which is the best \"collective\" outcome, but comes with a higher risk to the individual.",
            "This mutual defection - where rational self-interest leads to a poor collective outcome - is known as the Nash Equilibrium. In most of the cases, the end product almost always turns out to be the selfish mutual defection. Even when the activity is repeated, the result is most often this assured \"win\", due to a lack of trust.",
            "The real-world application of this strategic interaction is most evident in the market structure known as oligopoly, where a few large companies dominate the sector, but ironically their decisions completely depend on their competitors' actions.",
            "Consider the rivalry between substitute goods like Pepsi and Coke. Their market is a constant, real-time Prisoner's Dilemma, and they live under constant fear. If both companies cooperate by keeping prices high, both profit substantially. If one defects by initiating a price war (lowering prices), that company gains a short-term advantage, but the competitor is forced to retaliate. The end result is that both companies suffer reduced profit margins, trapped in the equivalent of the 3-year sentence.",
            "This competitive dynamic extends beyond pricing. Actions by a brand ambassador, such as Cristiano Ronaldo's famous decision to move Coke bottles aside in favor of water during a press conference, are moves that instantly impact the competitor's value and decision-making calculus. These companies live in a perennial crisis mentality, constantly seeking an upper hand in a game where their own decisions are completely dependent on the expected moves of the competition.",
            "Ultimately, the only way out of the \"Defect/Defect\" trap, whether in a high school project or a multi-billion dollar market, is through trust. The fundamental element that allows both the parties to move toward the wanted outcome is the confidence that the other side will not pursue a self-serving route, a confidence gained only through complete trust. Unfortunately, these days trust has almost become like a brittle chalk, and this scenario is like a game of chess where the players are scared to even make a move. In all strategic interactions, from the classroom to the world stage of climate negotiations and even oligopolies, the critical choice to be made remains: Trust or Bust.",
        ],
    },
    {
        "slug": "the-journey-behind-excellence",
        "title": "The Journey Behind Excellence",
        "issue": 29,
        "date": "February 2026",
        "author": "Aarav Bhartia | X B",
        "section": "Sport",
        "image": "the-journey-behind-excellence.webp",
        "image_alt": "Person climbing rocky steps toward a trophy",
        "image_width": 1374,
        "image_height": 1145,
        "image_caption": "Illustration supplied for the web edition.",
        "excerpt": "\"No, I cannot do it anymore\" - Have you said this to yourself in the middle of a 5,000 metres race? And later, regret the same while reflecting?",
        "paragraphs": [
            "\"No, I cannot do it anymore\" - Have you said this to yourself in the middle of a 5,000 metres race? And later, regret the same while reflecting? If you have, then you must read my journey in sports and how it shaped me.",
            "I was in grade 5. It had been 6 months since my school was shut down because of Covid-19. I was very bored. My father and I are die-hard fans of cricket, a group of people exclusively recognisable only to its members. Just as every kid's ambition changes daily, I decided to take a stand on a night of a cricket match. That night I said to my father, \"Papa, I want to play cricket.\" My father replied, \"Okay, we will go tomorrow morning.\" I said, \"No papa! I mean I want to become a cricketer.\"",
            "My father is the reason for whoever I am today and I hold nothing but gratitude to him. The next day, he went to the best academy in Nagpur and got me registered there. There were around five batches in the academy, from the basic to the advanced batch. Everyone had to join the basic batch and then, according to their progress, they got promoted to the higher batches. I was no exception. My coach used to bowl around 20 balls underarm, and that was counted as one set. Then all the players had to pick up all the balls and put it back into a tub so that the next batsman could play his set.",
            "On the first day, my coach did not allow me to touch the bat. I thought that maybe that is how everyone starts their training. The second day, I went with double my original enthusiasm, but was disappointed again. This continued on for one week, and my initial energy was exhausted. I started going to the ground late and stopped doing my warm ups properly. I complained to my father, \"Papa, the academy is a scam, they took money from you for me to pick up balls for other players.\" My father encouraged me by saying that it was probably part of the training.",
            "After 2 weeks, suddenly Coach gave me the bat and told me to defend the ball. After reflecting on it now, I realise that my coach wanted players who could stay committed to cricket no matter what. He was checking if I would come with the same energy every day, even if I was stuck between picking up the balls or quitting. Sometimes, life is just stuck at one level and that is when the majority of people quit, not realising how close they were to success.",
            "After my set, he saw how bad my technique was. My wrists were weak and I did not have the power to defend the ball. He made me do single hand defence every day until my left hand built strength. Every single day I would try my best to convince Coach with my improved batting, but every day I would go back disappointed. After 3 months, my defence became perfect. I had never been this patient in my life.",
            "Of course, with batting settled, the time came to start bowling. The coach took the choice to train me as a leg-spinner. I failed miserably. Every day the batsmen had to be careful of my bowling. Often, it was either a no ball or a dead ball. The batsman's job was not to hit the ball, but to pick up the ball after the wide. I practiced day and night and somehow got a stable and consistent line and length.",
            "This is when I learnt the power of consistency and hard work. If I was passionate about something and had the drive to be the best at it then nothing else would matter to me. I would not get distracted by small desires that would bring me one step down from my goal.",
            "Six months passed, I was still in the basic group and I started feeling that I had wasted a lot of my precious morning time and learnt very little cricket. Then suddenly one morning everything changed. In one of the senior most batches, a bowler ended up injured, and needed a substitute for a match immediately. The coach who trained that batch was walking around the nets and saw my bowling. He called me and asked, \"Match khelega?\" I was very scared of him. I had seen him yell at his players and punish them until they fainted. There was a mixed feeling inside me, of excitement and fear. I said, \"Haan sir, khelunga.\"",
            "That was the first official match I played. No one could believe I took 5 wickets that day and became the Man of The Match. The senior coach invited me to join his team. That day onwards, my life changed, and there was no looking back. I observed that opportunities always came to me, as long as I remained sincere in my practice. Not only in sport but in every field.",
            "My timings for training changed from 6 am to 4:30 am. My father used to wake up at 4, wake me up and we both used to be on the field at 4:30 am sharp. One hour we used to do intense fitness workouts. Then from 6 am to 8 am, cricket training.",
            "Today, whatever I have achieved in the field of sports is because of these 3 years. Along with increasing my stamina, it helped me make strong mindsets and commitments. I want to mention that you do not need talent to become successful. In fact, you need skills that do not take talent like punctuality, consistency and the spirit to outlast everyone else. If you are sincere in your passion then no one can stop you from becoming the best in the world.",
            "I know that I am a sum of the hard work of many people. This makes me more humble and motivates me to achieve more to make all of those people proud of me. I am still nothing and there is a long way to go.",
        ],
    },
    {
        "slug": "the-social-glue",
        "title": "The Social Glue",
        "issue": 17,
        "date": "July 2024",
        "author": "Raahi Tejas Shah | Crossroads Editorial Team ’24",
        "section": "The Editorial",
        "image": "the-social-glue.webp",
        "image_alt": "Illustrated sphere labelled with trust, empathy, dialogue and community",
        "image_width": 1672,
        "image_height": 941,
        "image_caption": "Illustration supplied for the web edition.",
        "excerpt": "The human brain evolved to navigate and maintain social structures of life. Primordially, we needed each other to survive.",
        # Issue 17 pp. 3-4: opening display lede is repeated in the prose.
        # The body follows the printed argument rather than the PDF text layer's column order.
        "paragraphs": [
            "The human brain evolved to navigate and maintain social structures of life. Primordially, we needed each other to survive. A tribe working together would survive, while a divided one died.",
            "In 2022, 1 in 5 believed that political violence was justified. The world we live in has increasingly begun to see itself as members of opposing squads.",
            "Of the many reasons we humans have brought up to account for our behavior, one is often blamed: social media. We blame it for making us more extremist and less empathetic, and emphasize the need to \"touch grass\" to escape into the real world. Sure, social media does have an effect on our brains, but maybe not the one you'd expect.",
            "Introducing you to the myth of the ‘filter bubble.’ Many of us have heard about online filter bubbles, where algorithms only show us content that we want to see. Of course, what we want are opinions that agree with ours, thereby omitting opposing views. In this poisonous hole, our view of the world narrows and becomes radicalized. But is that true? An extreme filter bubble is very rare, and studies have found very little evidence for its existence.",
            "The internet is a dump of information, and we are constantly confronted with contrasting views.",
            "The truth is that one is most ideologically isolated in one’s own life. We choose the people we closely interact with, and not too surprisingly, the interactions with people around you are much less diverse than the so-called online bubbles.",
            "The ‘filter bubble’ exists in our real lives, not online. Well then, what is the explanation behind humans turning against each other? Since social media constantly gives us diverse information, shouldn't it make us more open-minded and empathetic?",
            "Unfortunately, our brains are flawed.",
            "The human brain evolved to navigate and maintain social structures of life. Primordially, we needed each other to survive. A tribe working together would survive, while a divided one would die. That's why our brains had to make sure we cooperated. This propagates even today. Sure, you may dislike your neighbor, but since you live in the same area, you support the same cricket team and meet each other at the temple.",
            "As societies grew, we started meeting at shopping malls and town squares. Being physically close made us familiar to each other, and bridged the gap between different worldviews.",
            "Ancestrally, the people around us were similar to us. We liked what was similar to us, and this kept us together despite our differences. Everything was going smoothly until 20 years ago, when we created something that hit our brains like a train: the brand-new digital town square - social media.",
            "Our flawed brain is sorting people into teams, and so, the worst opinion is labeled, assigned, and generalized to everyone on that team (social community).",
            "Something that is striking is that everything that makes us individuals – the ice cream flavor we prefer, the shows we watch, our religions, our fashion sense, and so on – are constantly belittled, as if they are part of mutually exclusive rival teams.",
            "It seems as though the opposite team is almost willfully making the world a worse place, as though they are almost evil, beyond rationality and civil discussion.",
            "While we are on the correct team (obviously it's our team), it may be hard for us to realize that we may seem that way to the people on the other team.",
            "This contrast in belief suddenly becomes a central part of our identity. So, negative things about the \"other team\" are anchored upon and believed uncritically, whereas those who share your views are praised for their beliefs.",
            "People who think like you are added to your team. They are probably good people in your eyes, because any social group you belong to is good! Therefore, when you face negative information about your group, you dismiss it uncritically.",
            "Social media, driven by engagement, makes it worse, as it wants to keep you online for as long as possible. Well, the most engaging emotion is, unfortunately, anger. The angrier you get, the more likely you are to comment, share, and engage.",
            "This leads social media to amplify the most extreme and controversial opinions. It doesn't just show disagreements; it shows the worst of them.",
            "After this, our brains weren't able to handle the amount of disagreement they faced on social media, and we were not prepared for it. Our brains, in their attempt to simplify, sort everything into categories, whether you like it or not. People, things, and opinions all go into teams.",
            "Researchers call this ‘social sorting.’ On the digital town square, we encounter many people with clashing opinions, but unlike your neighbor, they don't root for your cricket team. You miss the local social glue your brain needs to connect with them.",
            "Essentially, we are dissolving the social glue that acts as a foundation for democracy.",
            "If we think our own neighbors are evil, how can we live together? Is there something we can do? Something more positive? In the end, it is important to be aware of what social media does to your brain and know that It's easier to change yourself than to change the world.",
        ],
    },
    {
        "slug": "death-of-detail",
        "title": "Death of Detail",
        "issue": 4,
        "date": None,
        "author": "Malhar Modi",
        "section": "Culture",
        "excerpt": "A long day at work, and you’re tired to the bone. You decide to visit the nearby park to finally take a break, and seat yourself on a bench.",
        "paragraphs": [
            "A long day at work, and you’re tired to the bone. You decide to visit the nearby park to finally take a break, and seat yourself on a bench.",
            "A few years ago, you’d be sitting on an elegantly carved bench, with ornate designs of animals, birds, or other urbane icons, but in the modern day, you’d be sitting on... this.",
            "This is just a small example of the wave of minimalism which is now taking over the world. This style has become the social default for seemingly every design choice, whether architectural, corporate or home décor. This is a troubling trend, because minimalism represents a very scary phenomenon – a distinct lack of detail.",
            "But why does detail matter? Think of it as an identity. What gave older phone boxes their distinct character? It was the details: a bright red color, moldings around the doors, ornamentation at the top. Now, the intricate detailing on phone boxes has vanished, and with it, their character.",
            "It is indeed true that beauty is in the eyes of the beholder, but this is not just about the beauty. Rather, it is about things having discernible qualities & characteristics which give them a unique identity. Take bollards, for example. Hardly anyone pays attention to them, but the older bollards had some character, even if they were hardly “beautiful”. Bollards nowadays? They just exist meaningless and mute.",
            "Gone are the elaborate throne-like lions, tigers and dragons which once adorned our furniture. Even park benches today have taken a turn towards minimalism.",
            "You’d need an expert to explain the significance behind our detailed temple architecture, and the symbolic meaning they convey. But modern skyscrapers? They don’t really say anything. They are just there. Huge boxes – plain, simple and above all, completely “mute”.",
            "As we move ahead, it’s time for us to look to the past. Recently, futuristis Indic art and Indic-themed art have flourished, with people taking to it like fishes to water.",
            "The most obvious feature of these futuristic Indic art pieces (such as Mukesh Singh’s works from Grant Morrison’s 18 Days) is the intrinsic detail which spreads beautifully across the entire canvas. This attention to detail can be found across all ancient civilizations.",
            "The worst crime of minimalist design is how it has stripped color from everything. From the temples of ancient India to the marvels of ancient Greece, each civilization told stories through their detailed artistry.",
            "The current social drift towards minimalism has stripped away all identity. Suddenly, everything looks the same - absolute neutrality.",
            "No details, no identity. The question is, what does this say about us as a people? Have we devolved from the glorious peaks of artistic evolution to being mute artists who have no life or light within our artistic expressions? Is minimalism leading to the death of detail, and the death of identity?",
            "In my opinion, this goes beyond the ephemeral world which we perceive. Intricate art seems to provide some knowledge through its details. It tries to convey some idea, some message. In a way, detailed art imposes something on us.",
            "Being fundamentally ego-driven beings, it has become a challenge for us to accept any form of imposition, which makes it easier for someone to appreciate minimalist, abstract designs having little to no substance of their own. Rather, they rely on the interpretation of the viewer, which boosts a person’s ego.",
            "This might also give us an insight into why Indian society as a whole always favored detailed art over highly individualistic, abstract and minimalist art forms.",
            "One of the fundamental values of the Indic society is a sense of collectivism, where collective dharma is valued more than individualism. It is not far reaching to actually believe that the strong collective knowledge-based identity of Indians made them lean more towards detailed art, which takes one away from individualism.",
            "Well, at least for the students of our school, minimalism is a reality very far away. From our various Masquerade art pieces to our incredibly expressive and detailed Wall Magazines, our students still seem to possess things to tell the world through their art.",
        ],
    },
    {
        "slug": "resurgence",
        "title": "Resurgence",
        "issue": 2,
        "date": None,
        "author": "Adhavan Diwakar",
        "section": "Culture",
        "image": "resurgence.webp",
        "image_alt": "Indian flag flying against a blue sky",
        "image_width": 1536,
        "image_height": 1024,
        "image_caption": "Photograph supplied for the web edition.",
        "excerpt": "Jana Gana Mana Adhinayaka Jaya He, Bharata Bhagya Vidhata!",
        "paragraphs": [
            "Jana Gana Mana Adhinayaka Jaya He, Bharata Bhagya Vidhata!",
            "The opening line of our national anthem proclaims; “Thou art the ruler of the minds of all the people, the dispenser of the destiny of India.” A powerful first line that glorifies that bhagyavidhata of India, who would go on to lead the country to greatness. However, a slight inaccuracy would rear its ugly head. The composer of the song, Rabindranath Tagore, had not, at least at first glance, left any clue as to the identity of this bhagyavidhata.",
            "Numerous instances throughout history have put on open display one core quality of the human race – the ability of the human race to concoct the most implausible theories where there is no set answer. Unfortunately, this situation would also fall victim to this human quality.",
            "The only hindrance to the common masses was the fact that even they did not have the slightest clue as to who this bhagyavidhata was. Conveniently, the King of England, King George the Fifth, was visiting India. Free to speculate and spread rumors, the people were quick to react, and very soon, a rumor was floating around.",
            "The Indian National Congress organized a ceremony to welcome the King to India. At the occasion, Tagore’s song was sung. It didn’t take long for people to connect two and two, and soon enough, rumors were spreading that this fated bhagyavidhata of India was none other than King George the Fifth.",
            "Available knowledge of our history compels us to question this popular assumption, how could this divine “dispenser of India’s destiny”, who was meant to guide India into the light, be a colonial overlord?",
            "The song's writer certainly felt the question posed was valid. Rabindranath Tagore was having absolutely none of it. Aghast by the speculations and rumors that had thoroughly desecrated the meaning of his composition, he was quick to debunk any claims under this umbrella. In a statement made to “a certain high official in Her Majesty’s service, who was also my friend”, he is quoted as saying; “I pronounced the victory in Jana Gana Mana of that Bhagya Vidhata of India who has from age after age held steadfast the reins of India’s chariot through rise and fall, through the straight path and the curved.",
            "That Lord of Destiny, that Reader of the Collective Mind of India, that Perennial Guide, could never be George V, George VI, or any other George.”",
            "Even after this not-so-subtle message to the masses that their guess was wrong, the notion stuck. Everyone still believed that the song glorified the ruler of the colonizers, King George the Fifth. However, among the crowd, there were a few that realized the untruth of the rumor. Those few were back to asking themselves the very first question - who, then, was this bhagyavidhata?",
            "At this point, one crucial fact must be taken into account. In 1911, Rabindranath Tagore wrote a five-stanza song in glorification of Bharat. When India’s founding fathers adopted the national anthem, they took only the first stanza of Tagore’s song and, as it would turn out, the answer to the widespread question on the identity of the bhagyavidhata of India would be present only a page length lower, in the third paragraph of this very same song.",
            "The third paragraph of the song proclaims; \"The way of life is somber as it moves through ups and downs, but we, the pilgrims, have followed it through ages. Oh! Eternal Charioteer, the wheels of your chariot echo day and night in the path In the midst of fierce revolution, your conch shell sounds.",
            "You save us from fear and misery. Oh! You who guide the people through torturous path, victory be to You, Dispenser of the destiny of India!",
            "Victory, victory, victory to You!\"",
            "On closer inspection, we make several interesting observations. First, is the mention of an “eternal charioteer”, guiding the nation on the path of dharma through the ages. Next, although not noticeable in the English translation, the timeless expression \"Yuge, Yuge” of the Bhagavad Gita fame, is used in the song. Finally, the song mentions chariots, conches, and various other iconographies all give us clues as to the identity of the real bhagyavidhata.",
            "Born in a prison cell in Mathura to Devaki and Vasudev, his very existence was to rid our world of adharma. Enlightening all of civilization with the Bhagavad Gita, he is truly one who fits Tagore’s description of this being. All those familiar with this dark-complexioned Lord will see an uncanny resemblance to Krishna in the third stanza of the song.",
            "An obvious question can be thrown at this assumption. How can a song containing religious iconography be adopted as the national anthem of a country which has a constitution classifying the country as secular?",
            "It would seem Tagore followed a pattern of hiding the answers to all questions about the song in the song itself. Let’s take a closer look at the second paragraph of the song, which goes; \"Your call is announced continuously, we heed Your gracious call The Hindus, Buddhists, Sikhs, Jains, Parsis, Muslims, and Christians, The East and the West come together, to the side of Your throne And weave the garland of love. Oh! You who bring in the unity of the people! Victory be to You, Dispenser of the destiny of India!",
            "Victory, victory, victory to You!\"",
            "Everyone reading this can be excused for scratching their heads and wondering what Tagore was thinking when he wrote this song. How could one song contain both religious symbols and phrases speaking about religious accommodation?",
            "Turns out that this idea was the very essence of Bharat. The concept that one can be rooted in their belief and practices and the concept that one can be accommodative of all faiths were never separate from each other. Instead, they were parallel concepts, coexisting side by side all across this land. The idea of religious pluralism was one underlying concept that constituted the core of this land throughout its history.",
            "Rabindranath Tagore’s song brings out such a beautiful concept that was deep-rooted in our civilization, but how many of us knew about it? So many of us did not know that our national anthem was only a part of a much bigger composition, yet, when we delve into its meaning, such profound information is revealed. Numerous such treasures exist all across the pages of our existence. Whether it be Aryabhata’s mathematical masterpieces or Sushruta’s surgical genius, let’s all take a moment and explore the many, many secrets that are hidden all across our civilization’s history.",
        ],
    },
]


def by_issue():
    """Newest issue first, and within an issue in the order listed above."""
    return sorted(POSTS, key=lambda p: -p["issue"])


def count():
    return len(POSTS)


def issues():
    return sorted({p["issue"] for p in POSTS}, reverse=True)
