#!/usr/bin/env python3
"""Build self-hosted WOFF2 fonts from a pinned upstream revision.

Requires fonttools[woff]==4.62.1 (only for this optional asset-generation step).
The ordinary site build needs no font tooling or network connection.
Full upstream glyph sets and OpenType shaping/variation tables are preserved.
"""
from io import BytesIO
from pathlib import Path
from urllib.parse import quote
from urllib.request import urlopen
import hashlib
import json
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'assets/fonts'
REVISION = 'f2bd09badbc763d8757951d52deec29da27e85fb'
BASE = f'https://raw.githubusercontent.com/google/fonts/{REVISION}/ofl/'
# A family may decline an italic by naming None for it. Jost does: it is here
# for one line of display lettering on CIRS Captures, and an italic nothing
# sets would be a second file the site downloads and never draws.
FAMILIES = [
    ('Newsreader', 'newsreader', 'Newsreader[opsz,wght].ttf', 'Newsreader-Italic[opsz,wght].ttf', '200 800'),
    ('Literata', 'literata', 'Literata[opsz,wght].ttf', 'Literata-Italic[opsz,wght].ttf', '200 900'),
    ('EB Garamond', 'ebgaramond', 'EBGaramond[wght].ttf', 'EBGaramond-Italic[wght].ttf', '400 800'),
    ('Tiro Devanagari Hindi', 'tirodevanagarihindi', 'TiroDevanagariHindi-Regular.ttf', 'TiroDevanagariHindi-Italic.ttf', '400'),
    ('Jost', 'jost', 'Jost[wght].ttf', None, '100 900'),
]

def put(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_bytes() != data:
        path.write_bytes(data)

def main():
    rules, manifest = [], []
    for family, slug, normal, italic, weights in FAMILIES:
        license_url = BASE + slug + '/OFL.txt'
        notice = urlopen(license_url).read()
        if b'SIL OPEN FONT LICENSE Version 1.1' not in notice:
            raise ValueError(f'Unexpected license for {family}')
        # Preserve the full notice while keeping generated text whitespace-clean.
        notice = b'\n'.join(line.rstrip(b' \t\r') for line in notice.splitlines()) + b'\n'
        put(OUT / 'licenses' / (slug + '-OFL.txt'), notice)
        for style, source in [('normal', normal), ('italic', italic)]:
            if source is None:
                continue
            url = BASE + slug + '/' + quote(source)
            raw = urlopen(url).read()
            font = TTFont(BytesIO(raw), recalcTimestamp=False)
            # Verify embedded metadata before declaring a CSS face; filenames are not evidence.
            axes = {a.axisTag: a for a in font['fvar'].axes} if 'fvar' in font else {}
            axis = axes.get('wght')
            embedded_weights = (f'{axis.minValue:g} {axis.maxValue:g}' if axis
                                else str(font['OS/2'].usWeightClass))
            embedded_style = 'italic' if font['OS/2'].fsSelection & 1 else 'normal'
            if embedded_weights != weights or embedded_style != style:
                raise ValueError(f'Face metadata mismatch for {family}: '
                                 f'{embedded_weights}, {embedded_style}')
            font.flavor = 'woff2'
            buffer = BytesIO()
            font.save(buffer)
            name = f'{slug}-{style}.woff2'
            data = buffer.getvalue()
            put(OUT / name, data)
            manifest.append({'family': family, 'style': style, 'weights': weights,
                             'file': name, 'source': url, 'license': license_url,
                             'source_sha256': hashlib.sha256(raw).hexdigest(),
                             'woff2_sha256': hashlib.sha256(data).hexdigest(),
                             'bytes': len(data)})
            rules.append(f"@font-face {{\n  font-family: '{family}';\n  font-style: {style};\n"
                         f"  font-weight: {weights};\n  font-display: swap;\n"
                         f"  src: url('../fonts/{name}') format('woff2');\n}}")
    put(ROOT / 'assets/css/fonts.css', ('/* Generated by tools/make-fonts.py. Local fonts only; licenses in assets/fonts/licenses/. */\n\n' + '\n\n'.join(rules) + '\n').encode())
    put(OUT / 'manifest.json', (json.dumps({'revision': REVISION, 'fonts': manifest}, indent=2) + '\n').encode())
    print(f'Built {len(manifest)} WOFF2 faces; {sum(f["bytes"] for f in manifest):,} bytes; {len(FAMILIES)} OFL notices retained.')

if __name__ == '__main__':
    main()
